### ISSUE TITLE
convert doesn't camelCase element attributes

### ISSUE THREAD

**Issue by diligiant** [FortAwesome/react-fontawesome#10]
icon composition creates a react component with a clip-path attribute whose name isn't camelized by convert before creating the element.

react mapping table is here just in case: [possibleStandardNames.js](https://github.com/facebook/react/blob/2b0f61a229fa2ff755d9e4daa701aa1181a71d41/src/renderers/dom/shared/hooks/possibleStandardNames.js)

**Comment by supercodepoet** [comment]
Should all be fixed up in 0.0.11
