### ISSUE TITLE
How to still allow for FontAwesome <i> tags to work?

### ISSUE THREAD

**Issue by SirNeuman** [FortAwesome/react-fontawesome#104]
I'm running into an issue where the `<i>` tags do not work on the same page as my react pages when using this package. It looks like the app prevents the `<i>` tags from being replaced by `<svg>` tags. So in my case my entire web app is not in React. The base of my html template is rendered server-side in Flask (using Jinja templating), with the rest (most) of my app being rendered in react within the Jinja container. The FontAwesome implementation works inside of the React portion of the app using this library, and the `<i>` tags work on pages where I do not use my React app (there are some pages where i do not import my React app at all, and there are just server-side forms used), just not inside the non-React portion of the template on pages where I do have my React app. 

I was wondering if there would be some sort of workaround for this? Even if it is a bit cumbersome that's okay, since there aren't many `<i>` tags in the base template (really just some icons in my navbar). Like maybe on pages where I am using React I could use jQuery to search find my `<i>` tags outside of the portion of the app (maybe based on a specific class name or something) and replace the `<svg>` tags manually?

**Comment by robmadole** [comment]
Hi @SirNeuman. We have a pre-release of this library (and the accompanying packages) that will take care of this for you. The `development` branch and this [chunk of documentation](https://github.com/FortAwesome/react-fontawesome/tree/development#processing-i-tags-into-svg-using-font-awesome) should get you going.

To get the correct versions make sure you reference the prerelease versions:

```
"@fortawesome/react-fontawesome": "0.1.0-7",
"@fortawesome/free-solid-svg-icons": "5.1.0-7",
"@fortawesome/fontawesome-svg-core": "1.2.0-10"
```

Also, [here is a codesandbox](https://codesandbox.io/s/9l05rn3m5o) that uses the new `dom.watch()` feature.
