### ISSUE TITLE
Why some icons are not available?

### ISSUE THREAD

**Issue by andrea-ligios** [FortAwesome/react-fontawesome#105]
Hi, I just want a clarification about why some icons (like Black-Tie: https://fontawesome.com/icons/black-tie?style=brands) are not implemented, and if/when they'll be (how it works in general, not the single icon... should their introduction be requested?)...
Thank you.

**Comment by robmadole** [comment]
@andrea-ligios are you asking about Font Awesome Black Tie? The entire style?

**Comment by andrea-ligios** [comment]
Sorry @robmadole, I'm not sure what you mean by "the entire style"; I just like to know why, among the icons listed here ( https://fontawesome.com/icons?d=gallery ), some icons are implemented and some other are not. I'd simply like to use the black-tie icon freely (solid, or whatever), and I was wondering if there's some kind of roadmap to know, or any action needed in order to accelerate the process.

**Comment by robmadole** [comment]
That icon is available now @andrea-ligios. What version of Font Awesome are you currently using?

**Comment by andrea-ligios** [comment]
I have

```
"dependencies": {
    "@fortawesome/fontawesome": "^1.1.5",
    "@fortawesome/fontawesome-free-regular": "^5.0.9",
    "@fortawesome/fontawesome-free-solid": "^5.0.9",
    "@fortawesome/react-fontawesome": "0.0.18",
```

**Comment by robmadole** [comment]
Can you put together a codesandbox.io or similar that illustrates the issue?

**Comment by andrea-ligios** [comment]
No need to, the issue bloody simple:

With (for example):
```
import faChartLine from '@fortawesome/fontawesome-free-solid/faChartLine';
```
I get the icon.

With:
```
import faBlackTie from '@fortawesome/fontawesome-free-solid/faBlackTie';
```
I get the following error:

![tmp](https://user-images.githubusercontent.com/11974750/38144948-4a8fcce4-3447-11e8-9549-72f9ba86d761.png)

Thank you for your help

**Comment by robmadole** [comment]
Ah, I see. That icon is part of the `fontawesome-free-brands` style. Give that a try.

**Comment by andrea-ligios** [comment]
Didn't know about a brand named BlackTie. 
It worked, thank you!
