### ISSUE TITLE
React.createElement error

### ISSUE THREAD

**Issue by nWidart** [FortAwesome/react-fontawesome#106]
Hello,

Since updating to `0.0.18`, I'm getting this in browser console:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

This was fixed by changing:

```js
import * as FontAwesomeIcon from '@fortawesome/react-fontawesome';
```

to 

```js
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
```

However, this breaks the tests.

To make the tests pass, it needs the `* as` part.

I'm confused on how to make it work for both browser and test.

Thanks!

**Comment by robmadole** [comment]
We are in the process of eliminating default exports. Can you try:

`import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'`?

**Comment by robmadole** [comment]
Actually @nWidart sorry that's not going to work. Let's get you over to the pre-releases to test this. Give me a second here.

**Comment by nWidart** [comment]
Thank you for the quick reply!

That named import works for the tests, but error remains in the browser.

**Comment by nWidart** [comment]
I tried on the prelease of react-fontawesome:

```
    "@fortawesome/fontawesome": "^1.1.5",
    "@fortawesome/fontawesome-free-solid": "^5.1.0-3",
    "@fortawesome/react-fontawesome": "^0.1.0-7",
```

But with this, all tests fail 😄 , some things like

```
Cannot find module '@fortawesome/fontawesome-svg-core' from 'index.js'
```

**Comment by robmadole** [comment]
Sorry @nWidart, had something come up.

Here is the new documentation for the pre-releases:

https://github.com/FortAwesome/react-fontawesome/blob/development/README.md

There is also an UPGRADING guide:

https://github.com/FortAwesome/react-fontawesome/blob/development/UPGRADING.md

Can you give these a try and let us know how that goes? We're very interested to see how we are doing and if those make sense.

**Comment by nWidart** [comment]
Thanks for the update, I'll check this out first thing tomorrow.

**Comment by nWidart** [comment]
The upgrade worked. No issues found yet. Upgrade guide was clear. 👍 

Thank you for the help!
