### ISSUE TITLE
Why is the default prefix for solid ("fas") rather than regular ("far")?

### ISSUE THREAD

**Issue by beausmith** [FortAwesome/react-fontawesome#107]
When passing a string as the value of `icon` the [default prefix is hardcoded for the solid font ("fas")](https://github.com/FortAwesome/react-fontawesome/blob/master/index.js#L491-L493).

Why not default the prefix to the regular font ("far")?

Using the Font Awesome Regular this doesn't work:

    <FontAwesomeIcon icon='circle' />

Instead I have to do this:

    <FontAwesomeIcon icon={['far', 'circle']} />

Seems that the default should be "far" and that if a user wants to use the solid, light, or brand fonts that they should have to pass a prefix.

**Comment by robmadole** [comment]
Hi @beausmith . It's because the "Solid" style most closely matches Font Awesome version 4 so it's less jarring of a transition for our previous version users. We won't be changing this default anytime soon. Thanks for sharing your thoughts on this.

**Comment by raymestalez** [comment]
Is it possible to add a setting to change this default?

**Comment by dpilafian** [comment]
While you would typically assume that something called **"regular"** would be the reasonable default over something called **"solid"**, there appears to be way more **"solid"** free icons.

`regular` - *All 152 Awesome Icons*
https://fontawesome.com/icons?d=gallery&s=regular&m=free

`solid` - *All 740 Awesome Icons*
https://fontawesome.com/icons?d=gallery&s=solid&m=free

Counterintuitively, **"solid"** might be the best default.

**Comment by mikael1000** [comment]
Anyone can confirm or link to something that says whats in op? That this is the RIGHT way to do it:

<FontAwesomeIcon icon={['far', 'circle']} />

**Comment by robmadole** [comment]
@mikael1000 `<FontAwesomeIcon icon={['far', 'circle']} />` is the correct way.

@PhilipsEkuma can you provide a reproduction we can take a look at?

**Comment by PhilipsEkuma** [comment]
Oh, I was doing it wrong. Social icons belong to the `<i class="fab fa-facebook">...</i>` category.

**Comment by silvinogustavo** [comment]
> Anyone can confirm or link to something that says whats in op? That this is the RIGHT way to do it:
> 
> <FontAwesomeIcon icon={['far', 'circle']} />
> 
> It don't work for me.

It doesn't work for me either

**Comment by InstantBuddha** [comment]
I had the same problem, what worked for me was:

after importing the needed icons: 

       import { faCheckSquare, faSquare } from '@fortawesome/free-regular-svg-icons'

I could simply refer to them, like:

       <FontAwesomeIcon icon={faCheckSquare} />
