### ISSUE TITLE
Add table of contents to README

### ISSUE THREAD

**Issue by robmadole** [FortAwesome/react-fontawesome#109]
See https://github.com/FortAwesome/vue-fontawesome/commit/3b1b48349b0bae1357a404157179cd54e7a06d4d for an example.

**Comment by sdabhi23** [comment]
Hey @robmadole I am interested in  helping out with this issue. But should I submit the PR against the master or the development branch??

**Comment by robmadole** [comment]
@sdabhi23 `master` would get great. We will only use `development` when we have a pre-release that we are testing. (Which we don't right now).
