### ISSUE TITLE
Can't install pro package with npm

### ISSUE THREAD

**Issue by Bobvantpadje** [FortAwesome/react-fontawesome#112]
I'm trying to install font-awsome for react by using npm but I can't seem to get it working. I ran the command to configure my font-awesome license. 

`$ npm config set @fortawesome:registry https://npm.fontawesome.com/TOKEN`

For TOKEN I used my personal NPM token which is displayed on the bottom of the page on the services tab, so I'm pretty sure I'm using the right token. 

After this I tried to run the commands to install the pro packages but they return a 404 error. I tried running my Powershell in adminstrator and restarting my Powershell but this didn't work either.

**Comment by Bobvantpadje** [comment]
Never mind. Just tried running the commands in command prompt instead of Powershell and they work. So I guess it's a Powershell bug.

**Comment by robmadole** [comment]
Well it's an escaping issue. You have to run `npm config set "@fortawesome:registry" https://npm.fontawesome.com/TOKEN` to make PowerShell happy.
