### ISSUE TITLE
Add TypeScript definitions for the package

### ISSUE THREAD

**Issue by rdsedmundo** [FortAwesome/react-fontawesome#115]
Would be great to have TypeScript support for the module, it could be placed here on the repository or at the DefinitelyTyped repo.

**Comment by robmadole** [comment]
Hey @rdsedmundo. We actually have this in the pre-release version of this lib.

https://github.com/FortAwesome/react-fontawesome/blob/development/index.d.ts

**Comment by rdsedmundo** [comment]
That's awesome! Thanks for the clarification. I'll wait for the release then, you may close the issue if you prefer.
