### ISSUE TITLE
font awesome works but icon component no

### ISSUE THREAD

**Issue by jfreixa** [FortAwesome/react-fontawesome#119]
Example code:
```js
// @flow
import * as React from 'react';
import fontawesome from '@fortawesome/fontawesome';
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
import light from '@fortawesome/fontawesome-pro-light';

fontawesome.library.add(light);

export default class Icon extends React.Component {
  render() {
    // works fine!
    console.log(fontawesome.icon({ prefix: 'fal', iconName: 'anchor' }));
    // logs Could not find icon { prefix: 'fal', iconName: 'anchor' } only on server side
    return <FontAwesomeIcon icon={['fal', 'anchor']} />;
  }
}
```
As you can see in the next image the first log works as expected but the icon component returns me the log of not found icon.
https://cl.ly/17470K2G3w2k

I'm using next.js and I had the icon component in a component library installed via npm. The error is only happening on the server side, not on the client side.

**Comment by robmadole** [comment]
Can you create a GitHub gist that reproduces this problem?

**Comment by jfreixa** [comment]
I will try to reproduce the issue as soon as possible thank you

**Comment by jfreixa** [comment]
Not able to reproduce the bug in standalone version.
