### ISSUE TITLE
Importing FA5 Pro Icons - Help

### ISSUE THREAD

**Issue by joniler** [FortAwesome/react-fontawesome#127]
It's unclear to me based upon the documentation provided whether or not I can import the "Pro" icon sets into my application. Is the full range of pro icons supported yet, or just the free ones? If so, what are the yarn package imports I should use for each icon set? Forgive me if this is a silly question.

**Comment by robmadole** [comment]
@joniler short answer is: you can.

We have a pre-release version of `react-fontawesome` that has better documentation.

You might give that a look: https://github.com/FortAwesome/react-fontawesome/tree/development

**Comment by leotm** [comment]
If [this](https://github.com/FortAwesome/react-fontawesome#add-more-styles-or-pro-icons) could get mentioned in [this](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers), it could save new devs a lot of time.
