### ISSUE TITLE
Prerelease hangs indefinitely with no output if built in production mode

### ISSUE THREAD

**Issue by JamesDonnelly** [FortAwesome/react-fontawesome#135]
I'm using Webpack 4. If I run `webpack --mode development`, everything builds as intended. If, however, I run `webpack --mode production`, nothing builds at all and the build just hangs, seemingly doing nothing forever.

I can understand why you'd want to block production mode builds of the development branch, but this problem left me quite confused for a while. I'm guessing this is a bug though, as I don't think it should hang without aborting.

**Comment by robmadole** [comment]
This is an issue with Webpack 4 and UglifyJS. Our recommendation is to switch to the [Babel plugin](https://github.com/webpack-contrib/babel-minify-webpack-plugin) or use deep imports like:

```
import { faCoffee } from '@fortawesome/free-solid-svg-icons/faCoffee'
```
