### ISSUE TITLE
Importing fontawesome-free-brands injects <style> even if autoAddCss is set to false

### ISSUE THREAD

**Issue by DamianPereira** [FortAwesome/react-fontawesome#136]
I'm using react_on_rails to render a website. I must include the CSS manually to be able to use fontawesome icons in server side rendering. I can include @fortawesome/fontawesome/styles.css contents inside my css bundle, but I can't disable the <style> injection in <head> when I include fontawesome-free-brands.

Versions I'm using (from my yarn.lock):

- @fortawesome/fontawesome-free-brands@^5.0.13
- @fortawesome/fontawesome@^1.1.8
- @fortawesome/react-fontawesome@^0.0.20

I have the following code in my application.js (client side entry file)

```
import fontawesome from '@fortawesome/fontawesome'
import brands from '@fortawesome/fontawesome-free-brands'
import faSearch from '@fortawesome/fontawesome-free-solid/faSearch'
fontawesome.config.autoAddCss = false
fontawesome.library.add(faSearch, brands)
```

But in the rendered HTML there is a <style> tag with fontawesome css (with classes such as fa-lg). If I remove the fontawesome-free-brands this does not happen, the following code produces no <style> tag (icons work since the required css is already in my CSS bundle).

```
import fontawesome from '@fortawesome/fontawesome'
import faFacebook from '@fortawesome/fontawesome-free-brands/faFacebook'
import faSearch from '@fortawesome/fontawesome-free-solid/faSearch'
fontawesome.config.autoAddCss = false
fontawesome.library.add(faSearch, faFacebook)
```
I've tried to do brands.config.autoAddCss = false, but it seems brands can't be configured since .config is undefined. I can use individual icons inside brands as a workaround, but I'd like to import them as a whole while preventing the injection.

**Comment by robmadole** [comment]
@DamianPereira can you try [switching to the pre-release version](https://github.com/FortAwesome/react-fontawesome/tree/development)? (it will be released pretty soon and is stable).

You'll be able to do the following:

```
import { library, config } from '@fortawesome/fontawesome-svg-core'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { faSearch } from '@fortawesome/free-solid-svg-icons/faSearch'

config.autoAddCss = false

library.add(faSearch, brands)
```

**Comment by DamianPereira** [comment]
This works as expected, and no longers injects css when importing. Thanks!

**Comment by borispoehland** [comment]
Is it possible to disable loading of the stylesheet when not using library, but direct imports?

```
import { faArrowRight } from '@fortawesome/pro-regular-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

return <FontAwesomeIcon icon={faArrowRight} />
