### ISSUE TITLE
Docs for react not at expected location

### ISSUE THREAD

**Issue by RichSnei** [FortAwesome/react-fontawesome#137]
The page: 
    https://fontawesome.com/preview/how-to-use/js-component-packages#react
indicates that we should go to:
    https://www.npmjs.com/package/@fortawesome/react-fontawesome
for the react api docs.

Unfortunately, the npmjs page only has the following message:

"Unable to find a readme for @fortawesome/react-fontawesome@0.0.20"

Not a big deal.  I found the docs on github.  I just thought you'd want to know.

**Comment by robmadole** [comment]
Ah, lovely. We do have docs for the pre-release which will be available very soon:

https://www.npmjs.com/package/@fortawesome/react-fontawesome/v/0.1.0-11

Thanks for the heads-up.
