### ISSUE TITLE
Error upgrading to 0.1.0 from 0.0.20

### ISSUE THREAD

**Issue by bmueller-sykes** [FortAwesome/react-fontawesome#147]
I hope I'm just missing something silly, but I get an error after upgrading to 0.1.0. My package.json has this:

```
    "@fortawesome/fontawesome": "1.1.8",
    "@fortawesome/fontawesome-free-solid": "5.0.13",
    "@fortawesome/fontawesome-free-regular": "5.0.13",
    "@fortawesome/react-fontawesome": "0.1.0",
```

...my icon config file is this:

```
import { library }  from '@fortawesome/fontawesome-svg-core'
import { regular } from '@fortawesome/free-regular-svg-icons'
import { solid } from '@fortawesome/free-solid-svg-icons'

library.add(regular, solid)
```

...and the file where I actually define my icons starts like this:
```
import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
...
```

...and when I start my React app, I get this error:

```
./node_modules/@fortawesome/react-fontawesome/index.es.js
Module not found: Can't resolve '@fortawesome/fontawesome-svg-core' in '/[my-local-path]/node_modules/@fortawesome/react-fontawesome'
```

I don't think I'm missing anything in the instructions. The only thing that looks like it might be wrong is that I'd expect the packages for `@fortawesome/fontawesome`, `@fortawesome/fontawesome-free-solid`, and `@fortawesome/fontawesome-free-regular` to be updated, but according to NPM, 1.1.8, 5.0.13, and 5.0.13 respectively are the latest versions of each package.

Help?

Thanks!

**Comment by bmueller-sykes** [comment]
wait...I might have figured out my stupidity...hang on...

**Comment by bmueller-sykes** [comment]
Okay, I've partially figured out my issue. The first problem is that my `package.json` needs to be this:

```
"@fortawesome/fontawesome-svg-core": "1.2.0",
"@fortawesome/free-solid-svg-icons": "5.1.0",
"@fortawesome/free-regular-svg-icons": "5.1.0",
"@fortawesome/react-fontawesome": "0.1.0",
```

...rather than what's listed above. 

The second problem was in my config file. It's now this:

```
import { library }  from '@fortawesome/fontawesome-svg-core'
import { far } from '@fortawesome/fontawesome-free-regular'
import { fas } from '@fortawesome/fontawesome-free-solid'

library.add(far, fas)
```

However, now I'm getting this error:

```
./src/config/configureIcons.js
Module not found: Can't resolve '@fortawesome/fontawesome-free-regular' in '/path/to/my/app
```

The `UPGRADING.md` file shows an example for importing `fontawesome-free-solid`, but not `fontaweome-free-regular`.  Again, I feel like I must be missing something really elemental here, but I can't figure it out. Help?

**Comment by robmadole** [comment]
```
import { library }  from '@fortawesome/fontawesome-svg-core'
import { far } from '@fortawesome/free-regular-svg-icons'
import { fas } from '@fortawesome/free-solid-svg-icons'

library.add(far, fas)
```

**Comment by robmadole** [comment]
Try that ^ @bmueller-sykes

**Comment by bmueller-sykes** [comment]
@robmadole Okay, it looks like that worked. here's my package.json code:
```
    "@fortawesome/fontawesome-svg-core": "1.2.0",
    "@fortawesome/free-solid-svg-icons": "5.1.0",
    "@fortawesome/free-regular-svg-icons": "5.1.0",
    "@fortawesome/react-fontawesome": "0.1.0",
```
...and here's my config file:
```
import { library }  from '@fortawesome/fontawesome-svg-core'
import { far } from '@fortawesome/free-regular-svg-icons'
import { fas } from '@fortawesome/free-solid-svg-icons'

library.add(far, fas)
```

What threw me was this line in UPGRADING.md:
`import { fas } from '@fortawesome/fontawesome-free-solid'`

...which should be:

`import { fas } from '@fortawesome/free-solid-svg-icons'`
