### ISSUE TITLE
can't find social media icons in the npm packages

### ISSUE THREAD

**Issue by FernandoBoza** [FortAwesome/react-fontawesome#149]
I installed and updated the import statements but can't find the social media icons in the font awesome library?

`import { faStroopwafel } from '@fortawesome/free-solid-svg-icons';`

I'm looking for the facebook, twitter, etc icons

**Comment by adambowles** [comment]
Brand icons will be in the [brand package](https://www.npmjs.com/package/@fortawesome/fontawesome-free-brands)

**Comment by johnludena** [comment]
Spent an embarrassing 45 minutes wondering why these were not showing up as part of the packages they suggest in the documentation. Please FontAwesome team, can you add this somewhere? 🥲
