### ISSUE TITLE
Re: One Year of Updates & Services for early backers?

### ISSUE THREAD

**Issue by diligiant** [FortAwesome/react-fontawesome#15]
([FAP issue #800](https://github.com/FortAwesome/Font-Awesome-Pro/issues/800))

@davegandy, reading your short post (and long in #772), I thought about the novel situation (at least for me) where a $$$ product accepts contributions on the side (I raise the issue here as I'm starting to be active here Cc @robmadole).

IMHO, it would be wise/nice if you thought of clear rules on how to thank people who will help you (back in the days, Apple would send me a new Mac every refresh cycle ;) And of course, the issue led me to think about waiving the U&S subscription.

It's not so much about money (some people out there make $1k/hour) but it is a nice gesture…

my 2¢

**Comment by Extarys** [comment]
Could be wise indeede **depending on the budget of the company**

**Comment by robmadole** [comment]
We'll keep this in mind @diligiant for those contributors who are making significant contributions. Thank you, sir.
