### ISSUE TITLE
Missing properties in Typescript typedefs

### ISSUE THREAD

**Issue by Rycochet** [FortAwesome/react-fontawesome#151]
Where this creates an SVG element, it doesn't (appear to) support any of the extra properties that are available and passed through - most notably `onClick` etc.

From the looks of the code it just passes through all unknown properties to the underlying React.CreateElement call.

I'm not sure if there's a best choice of what to do here, but the most inclusive one in this situation would be to change the `Props` interface slightly:

```typescript
export interface Props extends DOMAttributes<SVGSVGElement> {
    ...
}
```

**Comment by dangayle** [comment]
Fixed with https://github.com/FortAwesome/react-fontawesome/commit/b63b1ed030e9221865a459c09226246006bc75bd
