### ISSUE TITLE
Missing icons in the pro `index.d.ts` files

### ISSUE THREAD

**Issue by ekilah** [FortAwesome/react-fontawesome#153]
Not sure if this is the right place for this kind of report, but there are no public repos (that I know of) for the pro icons. Let me know if I should redirect this!

This icon: https://fontawesome.com/icons/file-upload?style=solid (and some others) seem to be missing from the `index.d.ts` types file (for Typescript) for all the pro icon packs.

`package.json` dependencies:

```
    "@fortawesome/fontawesome-svg-core": "^1.2.0-14",
    "@fortawesome/pro-light-svg-icons": "^5.1.0-11",
    "@fortawesome/pro-regular-svg-icons": "^5.1.0-11",
    "@fortawesome/pro-solid-svg-icons": "^5.1.0-11",
    "@fortawesome/react-fontawesome": "^0.1.0-11",
```

**Comment by esetnik** [comment]
I found the same thing after purchasing pro. Many of the icons are missing. I was looking for https://fontawesome.com/icons/medal?style=light and noticed it's not defined. It's not just that the typescript definition is missing, the icon itself is missing from the distribution `"@fortawesome/pro-light-svg-icons": "5.1.0-11"`

**Comment by esetnik** [comment]
[faAward](https://fontawesome.com/icons/award?style=light) is missing too

**Comment by ekilah** [comment]
looks like https://github.com/FortAwesome/react-fontawesome/issues/155 might be the same, haven't looked at this in a couple days. cc @esetnik i'll probably try it out tomorrow

**Comment by robmadole** [comment]
@ekilah @esetnik we've released the full `5.1.0` now which should include these. The pre-releases run a bit behind on including the icons.

**Comment by esetnik** [comment]
@robmadole we were told to use the `@prerelease` versions because we couldn't get 5.1.0 to work following the documentation provided. See https://github.com/FortAwesome/react-fontawesome/issues/101#issuecomment-377546926. Can you let us know when you will include the full pro icons in the `@prelease` version or alternatively when you will be releasing the `@prerelease`?

**Comment by robmadole** [comment]
@esetnik the prerelease has been fully released as 5.1.0

**Comment by esetnik** [comment]
@robmadole are these the correct package versions?

```
    "@fortawesome/fontawesome-svg-core": "^1.2.1",
    "@fortawesome/free-solid-svg-icons": "^5.1.1",
    "@fortawesome/pro-light-svg-icons": "^5.1.1",
    "@fortawesome/pro-regular-svg-icons": "^5.1.1",
    "@fortawesome/pro-solid-svg-icons": "^5.1.1",
    "@fortawesome/react-fontawesome": "^0.1.0",
```

**Comment by robmadole** [comment]
@esetnik those are correct. And `react-fontawesome` is versioned independently of Font Awesome so those versions are not going to match.
