### ISSUE TITLE
Missing icons in @fortawesome/free-solid-svg-icons^5.1.0-11

### ISSUE THREAD

**Issue by stijnvanderpol** [FortAwesome/react-fontawesome#155]
It appears I am missing some icons.

According to [the documentation](https://fontawesome.com/how-to-use/with-the-api/setup/importing-icons#packages) the [following icons](https://fontawesome.com/icons?s=solid&m=free) should be included in the free-solid-svg-icons package.  

However, I've noticed some icons (e.g. fa-file-export/faFileExport) are missing in `/node_modules/@fortawesome/free-solid-svg-icons/index.d.ts`

Is this intentional?

**Comment by ahafidi** [comment]
I've noticed that `faPen`, `faPencilRuler` and many other pens are missing as well.
```js
// @fortawesome/free-solid-svg-icons/index.d.ts
// line 397
export const faPaw: IconDefinition;
export const faPenSquare: IconDefinition; // ???
export const faPencilAlt: IconDefinition;
```

**Comment by canpan14** [comment]
You need to switch from the prerelease versions of the icon packages to 5.1.0 (-11 is prerelease).

**Comment by stijnvanderpol** [comment]
Yeah that fixed it, thanks :-)

**Comment by GiampaoloFalqui** [comment]
@canpan14 Sorry but what do you mean exactly? I am having the same issue.

This is my package.json:

```

[...]

dependencies: {
    [...]
    "@fortawesome/fontawesome": "^1.1.8",
    "@fortawesome/fontawesome-free-brands": "^5.0.13",
    "@fortawesome/fontawesome-free-regular": "^5.0.13",
    "@fortawesome/fontawesome-free-solid": "^5.0.13",
    "@fortawesome/react-fontawesome": "0.0.20",
    [...]
}

[...]

I tried to update all packages but without success (no update available).

**Comment by canpan14** [comment]
You need to change those three icon packages to version 5.1.0. Just do it manually. Because of the ^ you have the version is locked.

**Comment by GiampaoloFalqui** [comment]
This is what it says:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @fortawesome/fontawesome-free-solid@5.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-07-12T15_13_01_978Z-debug.log
```

**Comment by canpan14** [comment]
Oh my bad. If you look at the font awesome docs you'll see with the new versions of these packages you need to change the dependency names. The react font awesome docs walk you through the setup if you look at their page.

**Comment by GiampaoloFalqui** [comment]
Well...

![image](https://user-images.githubusercontent.com/4460702/42642580-723f3e44-85f7-11e8-95f4-646eaca31159.png)

This is indeed what it says, which is 5.1.0, but it does not seem to work.

**Comment by canpan14** [comment]
Without seeing your code it's hard to tell what's wrong. Make sure you follow the full documentation for switching to 5.1.0 there are multiple changes that need to be made. Including code changes

**Comment by m-adil** [comment]
I'm on `5.5.0` but still not getting `faWindows`:
```
'faWindows' is not exported from '@fortawesome/free-solid-svg-icons'`
```
