### ISSUE TITLE
Upgrading to 0.1.0 has slowed my app's build

### ISSUE THREAD

**Issue by JonAbrams** [FortAwesome/react-fontawesome#163]
Build time changed from 2m2.25s to 8m38s.

No other change other than upgrading my code to the new react-fontawesome modules and changing all my font import to use the new "tree-shaking" syntax.

I can confirm that only the needed fonts are being served up, but my builds are so much slower. Doesn't seem like a good trade-off. Unfortunately I needed to upgrade for a single new FontAwesome 5.1.0 font.

I'm using Next.js v6.1.1

**Comment by JonAbrams** [comment]
Switching to the suggested "non-tree shaking" version lowered the build time to 3m41s. I guess I'll just go with that:

```js
import { faFacebookF } from '@fortawesome/free-brands-svg-icons/faFacebookF';
```

**Comment by robmadole** [comment]
We have some information on this page @JonAbrams https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking
