### ISSUE TITLE
Missing free solid icon fa-file-signature from free-solid-svg-icons

### ISSUE THREAD

**Issue by itsca** [FortAwesome/react-fontawesome#171]
### Describe the problem

I need to use this icon: 
https://fontawesome.com/icons/file-signature?style=solid

On a navigation for my current project at work, although the regular and light versions of this icon are pro only, the solid version is part of the free set, yet is not being exported on:

-- index.d.ts 
or
-- index.es.js

of free-solid-svg-icons.

### What did you expect?

I would like to know if there's a reason for this icon not to be there or if it could be added.

Thank you.

**Comment by robmadole** [comment]
@itsca what version are you installing? I just checked and this icon is in version 5.1.0 (which is when it was added)

**Comment by itsca** [comment]
@robmadole Apologies that's correct, I got reverted on a recent merge to the first version I installed. Thanks for the response.
