### ISSUE TITLE
Upgrade version of Jest

### ISSUE THREAD

**Issue by sdabhi23** [FortAwesome/react-fontawesome#173]
The release of `v11.12.0` of JSDom has introduced some unexpected behavior in Jest, which causes all the tests to fail. It was discussed [here (#6766)](https://github.com/facebook/jest/issues/6766).

I has been fixed in `v23.5.0` of Jest or can be fixed by adding `testURL: "http://localhost"` to Jest config in older versions.  I strongly recommend upgrading the version in dependencies.

I have tested the changes and can confirm that everything else works as smoothly as it did with the older version of Jest.

**Comment by robmadole** [comment]
Awesome, I noticed that in the failing tests in CI but didn't track it down. I'll upgrade.
