### ISSUE TITLE
Installing the Pro icons results in a 404 from npm

### ISSUE THREAD

**Issue by dancrumb** [FortAwesome/react-fontawesome#175]
When I tried to install the Pro icons, I got a 404 from npm:

```
$ npm i --save @fortawesome/pro-regular-svg-icons           
npm ERR! code E404
npm ERR! 404 Not Found: @fortawesome/pro-regular-svg-icons@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/danrumney/.npm/_logs/2018-08-17T16_00_48_748Z-debug.log
```

**Comment by robmadole** [comment]
Hey @dancrumb send your log file to hello@fontawesome.com and we’ll take a look

**Comment by dancrumb** [comment]
Per our email exchange, I missed the instructions:

> Using the Pro packages requires [additional configuration](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers). 

If I'm in the minority with this issue, so be it, but I'm going to offer a small PR with a slight alteration to make it a little more obvious.
