### ISSUE TITLE
Error when loading far icons

### ISSUE THREAD

**Issue by sdubrez** [FortAwesome/react-fontawesome#177]
Hi

I'm trying to load far icons but I cannot make it work.

### Import
```
import { library } from '@fortawesome/fontawesome-svg-core'
import { faFlushed } from "@fortawesome/free-regular-svg-icons";
import { faFingerprint, faMapPin } from '@fortawesome/free-solid-svg-icons'
library.add(faFlushed, faFingerprint, faMapPin)
```

### Usage
`
 <FontAwesomeIcon icon={['far', 'flushed']} size='5x' color="#999" />
`

### Error

> Uncaught TypeError: Cannot read property 'prefix' of undefined

The error is fired when I'm adding the `faFlushed ` to the library.

Any tips ? Thanks in advance.

**Comment by robmadole** [comment]
@sdubrez check the version of `free-regular-svg-icons` you have installed. You need 5.1.0 or later to get `flushed`. If that still doesn't work then please provide a reproducible test case for us using something like codesandbox.io.
