### ISSUE TITLE
Compatibility on existing site using FA4

### ISSUE THREAD

**Issue by sbusch** [FortAwesome/react-fontawesome#182]
I'm aware that FA4 and FA5 shouldn't be mixed:

- <https://fontawesome.com/how-to-use/on-the-web/other-topics/troubleshooting#four-and-five>
- <https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#proofing>

BUT does this apply also when I add this React component (FA5 with SVG JavaScript method) to an existing site using FA4 via icon font?

**Comment by robmadole** [comment]
@sbusch yes, they are still incompatible as Font Awesome 5 still uses the same general CSS namespaces as version 4. They will conflict with each other.
