### ISSUE TITLE
How to access fa-xxx-o, say, fa-square-o icons?

### ISSUE THREAD

**Issue by nchiring** [FortAwesome/react-fontawesome#183]
I can use `<FontAwesomeIcon icon={faSquare} />` to avail fa-square. But how to achieve the same for fa-square-o ?

**Comment by robmadole** [comment]
@nchiring @PabloMessina any `fa-?-o` name has been moved to the "Regular" style. So [square](https://fontawesome.com/icons/square?style=regular) would be like this if you were using straight HTML:

```html
<i class="far fa-square"></i>
```

And with `react-fontawesome` it's:

```javascript
<FontAwesomeIcon icon={['far', 'square']} />
```
