### ISSUE TITLE
How to stack fontawesome icons in React?

### ISSUE THREAD

**Issue by PabloMessina** [FortAwesome/react-fontawesome#184]
Is it possible to stack icons? Is there any example in the official documentation of how this can be accomplished? The only example I could find is [this one](https://fontawesome.com/how-to-use/on-the-web/styling/stacking-icons) but that's just raw fontawesome and doesn't explain what the react version of doing the same is. Thanks in advance.

**Comment by robmadole** [comment]
@PabloMessina stacks have been replaced with "Layers". [Here is the example](https://github.com/FortAwesome/react-fontawesome#advanced).

**Comment by PabloMessina** [comment]
Oh I see. Thanks! One more question: will the CSS classes in the span wrapper work out-of-the-box, or do I need to explicitly import fontawesome CSS from, say, a CDN for it to work?

**Comment by robmadole** [comment]
The CSS is actually compiled into the JS. So when you use this component it gets included. You don't need to worry about external CSS.
