### ISSUE TITLE
HTML Props, custom attributes, and and aria-labels aren't being converted to valid HTML element tags

### ISSUE THREAD

**Issue by drewdecarme** [FortAwesome/react-fontawesome#19]
I'm having an issue with a few attributes that aren't being converted into HTML compliant element attributes correctly and React is throwing an error: I added the fields below

- **ariaHidden** (Warning: Invalid ARIA attribute `ariaHidden`. Did you mean `aria-hidden`?)
- **dataFaProcessed** (React does not recognize the `dataFaProcessed` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `datafaprocessed` instead. If you accidentally passed it from a parent component, remove it from the DOM element.)
- **dataPrefix** (React does not recognize the `dataPrefix` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataprefix` instead. If you accidentally passed it from a parent component, remove it from the DOM element.)
- **dataIcon** (React does not recognize the `dataIcon` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataicon` instead. If you accidentally passed it from a parent component, remove it from the DOM element.)

I'm using React 16+, importing the Font Awesome 5 Pro Light icons explicitly from a custom directory (since its not available in the free version), and then passing them down as props to a containing component that has the FontAwesomeIcon component inside of it.

I added a brief example below

```jsx
// FontAwesome is a webpack alias referring to where the custom font awesome assets are
// in this case it's where the light assets are stored
// Icons are passed as props when used
import { faRocket, faCog, faGroup, faBullhorn, faUser } from 'FontAwesome/light';

import FontAwesomeIcon from '@fortawesome/react-fontawesome';

export const Icon = ({ iconSize, icon, iconColor }) => (
  <div styleName={`${iconSize} ${iconColor}`}>
    <FontAwesomeIcon icon={icon} />
  </div>
);
```

**Comment by flood4life** [comment]
This was introduced in 0.0.11. Works correctly in 0.0.10.

**Comment by diligiant** [comment]
IMHO, we don't need the fa "data" properties. With React, it's just useless (we don't query/manipulate the DOM this way) and it bloats the rendering for nothing.

@supercodepoet and @robmadole do you have ideas on how to have ci "block" when the console screams errors and warnings (like it does on my setup)? It's important that we trust the release process. Please 😀

**Comment by supercodepoet** [comment]
This issue should be fixed up in 0.0.12. Keep in mind this is still an alpha component as we work through all the uses. I would welcome any tests to help firm this up.

**Comment by diligiant** [comment]
You are closing before it’s fixed?
Of course but please also help by not releasing when you get such console logs.
And if you’re unsure at this stage, PR and I’m sure lots of us will be happy to review.

**Comment by robmadole** [comment]
@diligiant huh?

**Comment by robmadole** [comment]
@diligiant ah, gotcha. no worries. Just making sure we didn't miss something.

**Comment by diligiant** [comment]
@robmadole don’t worry, you’ll hear for me ;)
