### ISSUE TITLE
Option to set autoReplaceSvg to 'nest'

### ISSUE THREAD

**Issue by tabby-or-not** [FortAwesome/react-fontawesome#195]
Using the `FontAwesomeIcon` component, it doesn't seem to respect the `@fortawesome/fontawesome-svg-core` config setting 'autoReplaceSvg' which I would like to set to nest. I can see that the `icon` function used in `FontAwesomeIcon` is using the `makeInlineSvgAbstract` method directly instead of using the mutator, so is this feature not available using `react-fontawesome`?

**Comment by robmadole** [comment]
@tabby-or-not it is not available for `react-fontawesome`. If you want to wrap the icon in another element you can simply do so in your own JSX.

The `autoReplaceSvg` is for automatic replacement of `<i>` tags with `<svg>`. If you are using `react-fontawesome` you don't need this.

Is there more to the store here than I'm guessing?

**Comment by tabby-or-not** [comment]
Just looking into swapping over to `react-fontawesome` but our site has mixed static html and react, so we'd still be using the `<i>` tags as well. I think the `nest` option is easier for people to understand when they come across it in future, but if it's not built in, we can add it in our jsx 👍
