### ISSUE TITLE
Please refactor the code, so it can be used with other jsx Libs like inferno js

### ISSUE THREAD

**Issue by chrkulbe** [FortAwesome/react-fontawesome#197]
Hi,

I've study your soure code and it seems, that 99% are independend of react.

Only the React.createElement and PropTypes in FontAwesomeIcon.js are react based.

If you will split FontAwesomeIcon.js in two files, one as FontAwesomeIconBase.js including the logic without react dependencies and default props as an exported constant instead of a property of the component, you and I can reassemble a FontAwesomeIcon.js for different Libs without dublicating code.

```javascript
// for react - FontAwesomeIcon.js
import FontAwesomeIconBase, {defaultProps} from './FontAwesomeIconBase'
import PropTypes from 'prop-types'
import React from 'react'

export default function FontAwesomeIcon(props) {
 return <FontAwesomeIconBase {...props} convertCurry={convertCurry}/>
}

FontAwesomeIcon.displayName = 'FontAwesomeIcon'

FontAwesomeIcon.propTypes = {
...
}

FontAwesomeIcon.defaultProps = defaultProps;

const convertCurry = convert.bind(null, React.createElement)
```

```javascript
// for inferno - FontAwesomeIcon.js
import { FontAwesomeIconBase, defaultProps} from '@fortawesome/react-fontawesome'
import { createElement } from 'inferno-create-element';

export default function FontAwesomeIcon(props) {
 return <FontAwesomeIconBase {...props} convertCurry={convertCurry}/>
}

FontAwesomeIcon.displayName = 'FontAwesomeIcon'

const convertCurry = convert.bind(null, createElement)
```

Thx

**Comment by robmadole** [comment]
Hmm. Inferno looks different enough to me that having a dependency on `react-fontawesome` doesn't fit in my opinion. I'd rather see a completely isolated implementation that is designed to work with that library. It would evolve on its own. Thanks for the recommendation but I'm :-1: on this.
