### ISSUE TITLE
Feature request: forwarding ref

### ISSUE THREAD

**Issue by gtkatakura-bysoft** [FortAwesome/react-fontawesome#199]
### Describe the problem you'd like to see solved or task you'd like to see made easier

Passing a ref through a `FontAwesomeIcon` to access `SVGElement`

### Is this in relation to an existing part of react-fontawesome or something new?

Related the component `FontAwesomeIcon`

### Why would other react-fontawesome users care about this?

Integration with APIs that use DOMElement (like the [Tooltip of reactstrap](http://reactstrap.github.io/components/tooltips/))

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?

7 - This year

### Feature request checklist

* [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
* [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
* [x] I have [searched for existing issues](https://github.com/FortAwesome/react-fontawesome/issues) and to the best of my knowledge this is not a duplicate

**Comment by andyrichardson** [comment]
Added to this, I think there is value in forwarding all the native element props:

```
  // Seperate FA props from SVG element props
  const { icon: iconArgs, mask: maskArgs, symbol, className, title, ...svgProps } = props;

  // ..
  // Inject svg props on render
  return <svg {...svgProps} >//...
```

Currently, in order to detect events such as `onMouseEnter` and `onHover`, it's required to wrap the FontAwesomeIcon component in a `span` element. 

Abstracting the svg element doesn't look to add any value and makes using the component more complicated.

**Comment by raRaRa** [comment]
Libraries such as `reactjs-popup` are unable to use `<FontAwesomeIcon />` as trigger since FA doesn't forward ref. I'm now required to wrap FA icons in span for trigger to work.

**Comment by jrolfs** [comment]
Looks like this was implemented in #220 and released recently in [v1.1.10](https://github.com/FortAwesome/react-fontawesome/releases/tag/0.1.10). I just wired it up in a project and it's working as expected, thanks :)

**Comment by davidalejandroaguilar** [comment]
I'm still getting this error:

```
index.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Icon___StyledFontAwesomeIcon`.
    in FontAwesomeIcon (created by Icon___StyledFontAwesomeIcon)
    in Icon___StyledFontAwesomeIcon (at Icon.js:32)
    in ForwardRef (at Task.js:165)
```

I'm rendering an icon like this:

```js
const Icon = React.forwardRef((props, ref) => {
  return <FontAwesomeIcon ref={ref} {...props}></FontAwesomeIcon>;
});

export default Icon;
```

My package versions:

```json
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/free-brands-svg-icons": "^5.14.0",
    "@fortawesome/free-regular-svg-icons": "^5.14.0",
    "@fortawesome/free-solid-svg-icons": "^5.14.0",
    "@fortawesome/react-fontawesome": "^0.1.11",
```

Any ideas?

**Comment by Avasam** [comment]
React-Bootstrap's [OverlayTrigger]() expects being able to use `ref`. Which forces us to write this in a very ugly way:
```js
const FaInfoCircle = forwardRef((props, ref) => <FontAwesomeIcon forwardedRef={ref} icon={faInfoCircle} {...props} />)
FaInfoCircle.displayName = 'FaInfoCircle'

[...]
    <OverlayTrigger overlay={<Tooltip id='somme-id'>Tooltip content</Tooltip>}>
      <FaInfoCircle />
    </OverlayTrigger>
[...]
```
rather than
```js
    <OverlayTrigger overlay={<Tooltip id='somme-id'>Tooltip content</Tooltip>}>
      <FontAwesomeIcon icon={faInfoCircle} />
    </OverlayTrigger>
```

**Comment by cpmsmith** [comment]
@robmadole Would you be open to reconsidering using `forwardRef`? React 16.3.0 will be 4 years old next week, and as https://github.com/FortAwesome/react-fontawesome/issues/199#issuecomment-868101220 points out, many libraries have come to assume it’s available in that time—another example not yet mentioned is [Tippy.js](https://github.com/atomiks/tippyjs-react). I get that it would be a breaking change, and React’s docs [explicitly recommend treating it that way](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers), but I still think it’d be worthwhile.

**Comment by robmadole** [comment]
@cpmsmith yep. I'm all for adding this if it's useful. I think my constraints would be that we try to make it backward-compatible and make sure there are adequate tests. I added the testing facility a while back (using GitHub matrix testing). So we should be able to dust off #220 and see where we are at. If it truly is a backward-incompatible change then we'd be looking at a major-version change and supporting `0.1.x` and `0.2.x` branches. I'd certainly devote time to get a PR merged if someone wanted to work on it with me.

**Comment by cpmsmith** [comment]
Nice, I can certainly help out with the PR. As far as making it backward-compatible, that [same docs page](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers) recommends against it:

> Conditionally applying React.forwardRef when it exists is also not recommended for the same reasons: it changes how your library behaves and can break your users’ apps when they upgrade React itself.

I don't necessarily feel strongly either way, but I see their point.

**Comment by robmadole** [comment]
@cpmsmith alright. that's fair. Let's have a `0.2` branch that can work for any React versions that support React.forwardRef.

**Comment by cpmsmith** [comment]
@robmadole I've opened #503 (and, along the way, #502) to implement this

**Comment by robmadole** [comment]
Thank you @cpmsmith . So helpful. We'll get some eyes on this as soon as we can.
