### ISSUE TITLE
Integrate react-fontawesome on nextjs 😶

### ISSUE THREAD

**Issue by jonathangiamp** [FortAwesome/react-fontawesome#203]
Hi everyone 👋

I use **nextjs** with **JSS** to styling my components. I want to be able to add **react-fontawesome** inside my project but I encoutered a problem to integrate the library functionnality.

I tried differents way to implement it but any of them work. Here a codesandbox with my code - [https://codesandbox.io/s/v6pyxp00w0](https://codesandbox.io/s/v6pyxp00w0)

The preview render of codesandbox seems break but all the code are on here. 
When I run my code, this error message is display on client and server consoles:

```
Could not find icon { prefix: 'fas', iconName: 'facebook' }
```

Do you think I should call the library function inside my *app.js* file instead of my *document.js*? Have you an idea to fix my problem?

Thanks you very much!

**Comment by jonathangiamp** [comment]
Fixed. To pass icon from `@fortawesome/free-brands-svg-icons` to `<FontAwesomeIcon />` component you need to override the suffix.
_Like that:_ **icon={['fab', 'facebook']}**

Good to know!

**Comment by rimsila** [comment]
>
