### ISSUE TITLE
Warning 'FontAwesomeIcon' expected 'number'

### ISSUE THREAD

**Issue by vimcat** [FortAwesome/react-fontawesome#204]
I'm setting the width and height on my icon per documentation. I get the Warning 'FontAwesomeIcon' expected 'number'.
```
import { FontAwesomeIcon } from '@fortawesome/react-native-fontawesome'
import { faUserCircle } from '@fortawesome/free-regular-svg-icons'

<View>
            <Text><FontAwesomeIcon icon={ faUserCircle } width='10' height='10' /> TEST</Text>
</View>
```

**Comment by jacobsowles** [comment]
I don't think `FontAwesomeIcon` has a `width` and `height` prop. For sizing, you use the `size` prop and pass it one of: `'lg',
    'xs',
    'sm',
    '1x',
    '2x',
    '3x',
    '4x',
    '5x',
    '6x',
    '7x',
    '8x',
    '9x',
    '10x'`

**Comment by jacobsowles** [comment]
Ah, you're using the react-native-fontawesome package. I missed that. You're right, the docs do say to use width="100" (though it also says they'll be moving to a `size` prop soon.

If you meant to use the native package, you may have better luck finding an answer over at the [react-native-fontawesome repo](https://github.com/FortAwesome/react-native-fontawesome).

If you don't actually want to use react native, switch your import to `import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'`, pass the `size` prop, and you should be good to go.

**Comment by vimcat** [comment]
Oh, sorry! I thought this was the native version. I'll post my issue there. Thanks!
