### ISSUE TITLE
Documentation of available props

### ISSUE THREAD

**Issue by JeffBaumgardt** [FortAwesome/react-fontawesome#21]
I noticed that in the readme the documentation of the props is a bit light. Is there any plan on updating the documentation listing all of the available props? Or are you holding off until the API is more solidified?

**Comment by robmadole** [comment]
@JeffBaumgardt we have plans to really expand the docs and put those on the main website. We are working furiously to get those done.

**Comment by JeffBaumgardt** [comment]
Thanks. Let me know if I can help.
