### ISSUE TITLE
fas,faCalendarDay icon is not available to export.

### ISSUE THREAD

**Issue by crayner** [FortAwesome/react-fontawesome#214]
I am trying to use a the faCalendarDay ICON found in the free-solid library of FontAwesome within a react app.  I import the required icons using 

```
    import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
    import { faCalendar, faCalendarPlus, faCalendarMinus, faUser } from '@fortawesome/free-regular-svg-icons'
    import { faSchool, faCubes, faCalendarDay } from '@fortawesome/free-solid-svg-icons'
```

but get an error icon not available for export on faCalendarDay.  I found that the calendar-day definition is missing from the @fortawesome/fontawesome-common-types/index.d.js in the node_modules directory.  Adding 'calendar-day' in this file 3 times fixed the issue.  I would do a pull and repair myself but I am unable to find these files in a repository. Sorry.

Craig

**Comment by robmadole** [comment]
Hi @crayner. If you can provide a complete reproduction of this we'll give it a look. You can use codesandbox.io or something similar.

**Comment by crayner** [comment]
The definitions for faCalendarDay are missing from the  from the common types index file.  Add them there, and the system works as expected.  SO in my 
...\node_modules\@fortawesome\free-solid-svg-icons\node_modules\@fortawesome\fontawesome-common-types\index.d.ts
I added   'calendar-day' | 
at lines 639,2117 and 3595, as the Font Awesome website states that faCalendarDay is a free solid icon.  Hope this helps.  (I would have done a pull request, but this repository structure is nothing like the installed content, and I did not wish to take the time to find the appropriate file.)

**Comment by robmadole** [comment]
@crayner I've verified that the file `faCalendarDay.js` and `faCalendarDay.d.ts` exist in `@fortawesome/free-solid-svg-icons`. I also verified that the `calendar-day` icon name exist in the `@fortawesome/fontawesome-common-types` library.

You might check the versions you have installed and update the dependencies. That's the easiest thing to check. If you still have trouble we _must_ have a reproducible test case using something we can run locally or through a code-sharing site. It's too difficult to debug issues in a JS app without it. I'll re-open this issue if you are still having problems and provide the test case.

**Comment by crayner** [comment]
Thanks,
Is the latest version 0.1.03 because that is what I am using.  Is that the
latest version?  It is a little disappointing to see that you are not
willing to correct an error when the solution is given so clearly.

------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Mobile: +61 456 560 018

**Comment by robmadole** [comment]
@crayner we don't have a 0.1.03 of anything, that's not how we version our libraries or packages. That's the primary reason that we ask our community to provide a reproducible example. There is a lot of ambiguity in your reported issue. And regarding the solution that you gave, we literally can't make that fix because I have verified that there is no issue in the packages that you referred to. That icon exists in those packages.

Are you not willing to provide a reproducible example? I have requested it twice now. The time investment on your end almost always resolves with a fix that will solve your issue. The alternative is that we go round and round, each of us guessing the other one's meaning and very seldom solving the problem.

**Comment by crayner** [comment]
Ah, Then perhaps I am on the wrong thing.  Thanks.

I pull this from the ChangeLog file

# Change Log

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/)
and this project adheres to [Semantic Versioning](http://semver.org/).

---

## [0.1.3](https://github.com/FortAwesome/react-fontawesome/releases/tag/0.1.3)
- 2018-09-06

### Added

- Add title prop #180

---

## [0.1.2](https://github.com/FortAwesome/react-fontawesome/releases/tag/0.1.2)
- 2018-08-12

### Changed

- Better table of contents in README.md #172

---

## [0.1.1](https://github.com/FortAwesome/react-fontawesome/releases/tag/0.1.1)
- 2018-08-07

### Changed

- Added tabIndex to TypeScript definitions #168


and then from github

Change Log

All notable changes to this project will be documented in this file.

The format is based on Keep a Changelog <http://keepachangelog.com/> and
this project adheres to Semantic Versioning <http://semver.org/>.
------------------------------
<https://github.com/FortAwesome/react-fontawesome/blob/master/CHANGELOG.md#014---2019-01-15>
0.1.4 <https://github.com/FortAwesome/react-fontawesome/releases/tag/0.1.4> -
2019-01-15
<https://github.com/FortAwesome/react-fontawesome/blob/master/CHANGELOG.md#changed>
Changed

   - Upgrade to Babel 7 and Rollup 1 #213

<https://github.com/FortAwesome/react-fontawesome/blob/master/CHANGELOG.md#fixed>
Fixed

   - Thrown error in IE11

------------------------------
<https://github.com/FortAwesome/react-fontawesome/blob/master/CHANGELOG.md#013---2018-09-06>
0.1.3 <https://github.com/FortAwesome/react-fontawesome/releases/tag/0.1.3> -
2018-09-06
<https://github.com/FortAwesome/react-fontawesome/blob/master/CHANGELOG.md#added>
Added

   - Add title prop #180

------------------------------
<https://github.com/FortAwesome/react-fontawesome/blob/master/CHANGELOG.md#012---2018-08-12>
0.1.2 <https://github.com/FortAwesome/react-fontawesome/releases/tag/0.1.2> -
2018-08-12

I hope you can understand my confusion, especially as the site names on
GitHub are the same?

------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Mobile: +61 456 560 018
