### ISSUE TITLE
Looks like shit in Safari?

### ISSUE THREAD

**Issue by alxvallejo** [FortAwesome/react-fontawesome#221]
![image](https://user-images.githubusercontent.com/947203/52169405-c1211000-2705-11e9-8325-4eb2659aaaa0.png)
^ in Safari

vs

![image](https://user-images.githubusercontent.com/947203/52169409-ce3dff00-2705-11e9-9ac0-ffbd1b86e270.png)
^ in Chrome

No one else is having this issue?

Here's my simple import and render:

```
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faHome, faAlignLeft } from "@fortawesome/free-solid-svg-icons";

<button onClick={() => this.getArticle(post, i)}>
    <FontAwesomeIcon icon={faAlignLeft} inverse />
</button>
```

**Comment by jacobsowles** [comment]
If you check out the button in the inspector, are there any default styles in Safari that might be causing this issue?

**Comment by robmadole** [comment]
@alxvallejo if you can post a reproducible example using something like codesandbox.io we'll be glad to take a look. Going to close as there has been no response to @jacobsowles question.
