### ISSUE TITLE
Icons not clickable when used in conditional elements

### ISSUE THREAD

**Issue by xhudaman** [FortAwesome/react-fontawesome#222]
The icons are not clickable when rendered inside conditional elements, however the rest of the element surrounding the icon is.
I am using the newest React-Fontawesome alongside React 16.6.3 and Bootstrap 4.1.3.

**Comment by robmadole** [comment]
@xhudaman please post an example using something like codesandbox.io and we'll be happy to take a look.

**Comment by xhudaman** [comment]
Sorry about the time it took me to get this set up!

[Here](https://codesandbox.io/s/w28ov0jpz5) is a working example of my issue in CodeSandbox.

Thanks for the help!

**Comment by robmadole** [comment]
@xhudaman you have to be careful using props from an `event.target`. The subtle thing here is that depending on _where_ the click occurs the `event.target` can either be the `<button>` or the `<FontAwesomeIcon>`. Since you are pulling a prop off the button (`.name`) if you click the icon directly that prop isn't present (it is actually on the `event.target.parentNode` though!)

Here's a fixed version: https://codesandbox.io/s/nk3z8kk1wl

**Comment by xhudaman** [comment]
That seems like a bit of a hack to me rather than a proper use case.  Regardless, it's not possible to assign the icon's JSX element an id of it's own.  That is a problem in it's own right. 
Use of event.target.parentNode becomes quickly and easily unreadable.

**Comment by robmadole** [comment]
You mean my solution seems like a hack? You might check out Reacts documentation on this. It's what they recommend. https://reactjs.org/docs/handling-events.html

**Comment by nileshp07** [comment]
> @xhudaman you have to be careful using props from an `event.target`. The subtle thing here is that depending on _where_ the click occurs the `event.target` can either be the `<button>` or the `<FontAwesomeIcon>`. Since you are pulling a prop off the button (`.name`) if you click the icon directly that prop isn't present (it is actually on the `event.target.parentNode` though!)
> 
> Here's a fixed version: https://codesandbox.io/s/nk3z8kk1wl

I m looking for the exact thing which you have shown in your browser but with pure javascript ....can you please show how to do this with pure js
