### ISSUE TITLE
fa-w widths applied

### ISSUE THREAD

**Issue by flyfishMT** [FortAwesome/react-fontawesome#224]
I am using FontAwesome icons in a react-bootstrap left nav menu, and when the react component is rendered, they have different width classes applied so they don't line up:
```
import {
  faWalking,
  faSwimmer
} from "@fortawesome/free-solid-svg-icons";
<Nav>
<Nav.Link><FontAwesome icon={faWalking} /> Walking<Nav.Link>
<Nav.Link><FontAwesome icon={faSwimmer} /> Swimmer<Nav.Link>
</Nav>
```

When rendered:
```
<a class="nav-link>
<svg class="svg-inline--fa fa-walking fa-w-10"....>
</a>
<a class="nav-link">
<svg class="svg-inline--fa fa-swimmer fa-w-20"...>
</a>
```

Can I make them have equal widths?

**Comment by Flixbox** [comment]
How did you solve this?

**Comment by flyfishMT** [comment]
> 
> How did you solve this?
> 

Yes, I used fixedWidth.  Thanks
