### ISSUE TITLE
Icon color cannot be animated with CSS Transitions

### ISSUE THREAD

**Issue by alflennik** [FortAwesome/react-fontawesome#229]
### Describe the problem

I added CSS to add a transition to the fill:

```css
path {
  transition: fill 1s linear;
}
```

And then I changed the fill color in Chrome devTools and watched it transition over 1 second 👍

Then I used a dynamic color prop for the FontAwesomeIcon:

```js
<FontAwesomeIcon icon={faStar} color={iconColor} />
```

But there is no transition when it switches between colors.

### What did you expect?

The color prop should be animatable _somehow_, whether it be through CSS transitions or another means.

### Reproducible test case

https://codesandbox.io/embed/w72300rk4l

**Comment by petertriho** [comment]
I recommend you change your css  from
```
.icon svg > path {
  transition: fill 1s linear;
}
```
to
```
.icon svg {
  transition: color 1s linear;
}
```

**Comment by robmadole** [comment]
Try this @alflennik https://codesandbox.io/s/p3xq0jyjrx
