### ISSUE TITLE
Can't disable CDN

### ISSUE THREAD

**Issue by PerfectionCSGO** [FortAwesome/react-fontawesome#238]
We would like to disable CDN but this does not seem possible with provided documentation? Unless I did not find it.

Situation: It seems like react-fontawesome works based on the '//' protocol which automatically resolves to https:// or http:// but in an electron application this will not work as production builds serve with file://. 

I encountered this problem while testing a production build that was starting very slowly (Window would not show until dom was ready).

This is what we percieve:

![image](https://user-images.githubusercontent.com/16305895/57528114-b512a300-7331-11e9-8bca-72d472895d60.png)

**Comment by PerfectionCSGO** [comment]
Nevermind that. We resolved it.

**Comment by iamkhalidbashir** [comment]
How?
