### ISSUE TITLE
Problem in installation on npm - Error messages

### ISSUE THREAD

**Issue by itayperry** [FortAwesome/react-fontawesome#240]
Why do I get these messages when I use (no matter which) installition command?

`npm WARN @typescript-eslint/eslint-plugin@1.6.0 requires a peer of typescript@*          but none is installed. You must install peer dependencies yourself.                      npm WARN @typescript-eslint/parser@1.6.0 requires a peer of typescript@* but non         e is installed. You must install peer dependencies yourself.                             npm WARN @typescript-eslint/typescript-estree@1.6.0 requires a peer of typescrip         t@* but none is installed. You must install peer dependencies yourself.                  npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You          must install peer dependencies yourself.                                                npm WARN tsutils@3.10.0 requires a peer of typescript@>=2.8.0 \|\| >= 3.2.0-dev \|\|          >= 3.3.0-dev \|\| >= 3.4.0-dev but none is installed. You must install peer depen         dencies yourself.                                                                        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\cho         kidar\node_modules\fsevents):                                                            npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@         1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}         )                                                                                        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\jes         t-haste-map\node_modules\fsevents):                                                      npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@         1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}         )                                                                                        npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.6 (node_modules\fse         vents):                                                                                  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@         2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}         )                                                                                                                                                                                 + @fortawesome/fontawesome-svg-core@1.2.18                                               added 2 packages from 6 contributors and audited 888975 packages in 17.522s              found 0 vulnerabilities`
--

**Comment by robmadole** [comment]
This isn’t related to Font Awesome. What makes you think this is a ‘react-fontawesome’ issue?

**Comment by itayperry** [comment]
I'm very sorry, my bad :) I thought it had something to do with this message, but I was wrong.
Thank you for closing the issue.

**Comment by datatalking** [comment]
@itayperry I am experiencing the same issue, how did you solve this?

$ npm i @typescript-eslint/eslint-plugin --save-dev
npm WARN @typescript-eslint/parser@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/typescript-estree@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@1.6.0 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@1.10.2 requires a peer of @typescript-eslint/parser@^1.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.14.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/experimental-utils@1.10.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.

**Comment by 2mdipro7** [comment]
I am facing the same problem. Quite amazed that there isn't one solution anywhere.
![image](https://user-images.githubusercontent.com/47535837/60492490-e9209980-9ccc-11e9-8da5-925dd33a2451.png)

**Comment by luisalmeida12** [comment]
Same problem here.
Is there any solution ?

**Comment by robmadole** [comment]
Everyone, please read the messages carefully. It's telling you that a dependency depends on something else. Most likely `npm install --save typescript` would solve @datatalking 's problem.
