### ISSUE TITLE
Invalid prop `style` of type `array` supplied to `FontAwesomeIcon`, expected `object`

### ISSUE THREAD

**Issue by dallasclark** [FortAwesome/react-fontawesome#245]
**Describe the bug**

When wrapping the `<FontAwesomeIcon>` component with a `<TouchableHighlight>`, the following warning is shown after clicking/tapping the component:

```
Warning: Failed prop type: Invalid prop `style` of type `array` supplied to
`FontAwesomeIcon`, expected `object`.
```

The warning will only appear once.

**Reproducible test case**

```
<TouchableHighlight
    onPress={() => self._navigateToProductScreen('10830813')}>
    <FontAwesomeIcon
        icon={ faBarcode }
        size={ 40 }
        style={ styles['camera-view-button'] } />
</TouchableHighlight>
```

**Expected behavior**

No warnings shown.

**Desktop (please complete the following information):**

- iOS Simulator (iPhone X iOS 12.2)
- iPhone X (iOS 12.3.1)

**Additional context**

<img width="545" alt="Screen Shot 2019-06-04 at 11 44 59 am" src="https://user-images.githubusercontent.com/542948/58845395-5a653080-86be-11e9-879b-350417a21d98.png">

**Comment by robmadole** [comment]
The style property must be an object. Like `{ color: 'red' }`, not an array.

**Comment by genesy** [comment]
I get this same error even without setting a style prop on the FontAwesomeIcon component. also tried setting an object and still get the same error 
```
<TouchableHighlight onPress={()=> {}}>
   <FontAwesomeIcon icon={faHeart}/>
</TouchableHighlight>```
error appears when i trigger the onpress on the icon. This error shows up on my android simulator

**Comment by robmadole** [comment]
@genesy are you using React-Native? We have a different component that might work better for you. Check it out at https://github.com/FortAwesome/react-native-fontawesome

**Comment by genesy** [comment]
Oh. I'm actually using that. Just googled the issue and got here, will report issue there. Thanks
