### ISSUE TITLE
FontAwesomeIcon is not memoized

### ISSUE THREAD

**Issue by suppayami** [FortAwesome/react-fontawesome#249]
**Describe the bug**
FontAwesomeIcon component is not memoized by default, this would cause the icon to be re-rendered every time its parent gets re-rendered.

**Expected behavior**
The component should be memoized by default, either by using PureComponent or React.memo(component) wrapper.

**Comment by crimx** [comment]
If a icon is bound to change with its parent then this would only casue an extra check. I think this should leave it to the user or expose another cached Component.

**Comment by suppayami** [comment]
An extra check per icon pollutes profiler so much a for normal page. Expose a cached component is fine, though memoizing the existing component is preferred. There is no trade-off to this approach.

**Comment by crimx** [comment]
> There is no trade-off to this approach.

Shallow equal is not cheap either. And there is no way to "unmemoize" a Component.

**Comment by avin-kavish** [comment]
Memoization can be performance optimization made by the user as they see fit, there is no need for this library to provide it.

**Comment by robmadole** [comment]
Yeah, sorry @suppayami but this is overly aggressive. I'd be happy to post some information in the docs about this if you think it's useful. But changing the component has too many implications that are hard to untangle and risky to force on everyone in a patch or minor release.
