### ISSUE TITLE
"svg-inline--fa" and "fa-w-14" are applied by default, how can I disable this?

### ISSUE THREAD

**Issue by ell10t** [FortAwesome/react-fontawesome#252]
I'd rather supply my own styles, is there any method to disabling these defaults?

**Comment by robmadole** [comment]
@ell10t no. These are critical to making the icons display correctly. You are welcome to use the source SVG files available in the `@fortawesome/fontawesome-free` or `@fortawesome/fontawesome-pro` package. You can also use the `@fortawesome/fontawesome-svg-core` package and [modify icons using JS](https://fontawesome.com/how-to-use/with-the-api/methods/icon).
