### ISSUE TITLE
sort-amount-down-alt (and others) missing from @fortawesome/free-solid-svg-icons

### ISSUE THREAD

**Issue by vincerubinetti** [FortAwesome/react-fontawesome#255]
The [sort-amount-down-alt](https://fontawesome.com/icons/sort-amount-down-alt?style=solid) icon (marked as free on fontawesome.com) and most likely several other `alt` icons are missing from `@fortawesome/free-solid-svg-icons` version `5.9.0` (latest according to npm).

![image](https://user-images.githubusercontent.com/8326331/61078244-351abf00-a3ee-11e9-985f-4b39e09d35ff.png)

I checked all the exports from the module with the method below, and I can't find it under any name. This one would be really nice to have!

```
var exports = require('@fortawesome/free-solid-svg-icons');
console.log(Object.keys(exports).filter(entry => entry.toLowerCase().includes('sort')));
```

**Comment by robmadole** [comment]
@vincerubinetti I just checked and this icon is present. Can you double-check? Line 5552 of `@fortawesome/free-solid-svg-icons/index.js` shows it. And the `faSortAmountDownAlt.js` icon is in the same directory.

I'll re-open if you still think this is missing but I'll need some additional places to look.

**Comment by vincerubinetti** [comment]
Sorry, it is there. I don't know what happened. Maybe I was delirious that day. Thank you.

**Comment by robmadole** [comment]
No worries! Glad it wasn't a bug 😬!
