### ISSUE TITLE
[question] Is it possible to avoid replacing <i> to <svg>?

### ISSUE THREAD

**Issue by aralroca** [FortAwesome/react-fontawesome#256]
I've noticed that if I use the same icon in a lot of places of my page (for example in a list), then the source code of this page is huge! With a lot of `<svg>` content duplicated.

I would like to understand the benefit of replacing `<i>` to `<svg>` tags. I feel that using `<i>` have more benefits for my Next.js app, at least:

* Static content that don't need to rehydrate
* Less duplicated code and smaller source code (HTML)

Currently I'm trying to improve the performance of my app and I see that maybe this can be improved from my side. However I don't know the real motive of this replacement and if can be avoided. I will appreciate if somebody can clarify me 🙂 Thank you!

**Comment by robmadole** [comment]
@aralroca SVG provides more features. We can do things like power transforms and masking.

You might check out the [docs on symbols](https://fontawesome.com/how-to-use/on-the-web/advanced/svg-symbols) if you have a lot of repeating icons on your page.

Otherwise, if the web fonts implementation works better for you then go for it! We provide a lot of different implementations so that everyone can choose what works best for them.

**Comment by burka** [comment]
Wouldn't it be possible to make the svg-use you described easily accessible to anyone using react-fontawesome? It would be great to form some libraries that one could render on those pages with icon lists.

**Comment by robmadole** [comment]
@burka this is already possible with react-fontawesome. Maybe I'm not smelling what your cookin'?

**Comment by burka** [comment]
We have a 2000 row list with up to 5 icons in each row. The list is virtualized. After or while scrolling up to 40(rows)x5 icons are drawn, which slows down everything and is the slowest part in the list. On slow computers that adds 200ms to the rendering.

In the [docs on symbols](https://fontawesome.com/how-to-use/on-the-web/advanced/svg-symbols) you referenced svg-use.

```
<!-- Name symbols with the value of data-fa-symbol -->
<i data-fa-symbol="picture-taker" class="fas fa-camera"></i>

<!-- Use the defined name -->
<svg><use xlink:href="#picture-taker"></use></svg>
```
I thought it would be awesome if some outer element (outside of the list) could collect the used icons (or be configured for those icons) that those icons in the list are only references that use `<svg><use>...` which would speed up the rendering dramatically as they don't need to be reparsed as new dom content.

**Comment by robmadole** [comment]
Ah, I see. This is an interesting idea but I'm not 100% convinced that this isn't just a premature optimization for a lot of folks. It also has garbage collection implications (do these icons live forever in a global kind of bucket)? Really cool idea though.

**Comment by burka** [comment]
The element to collect the icon library could be a explicit parent element whoose children use it if it is available. If not the current behavior could take place. That way everybody would have controll of it and could remove it to purge the cache. Or supply a purge=true attribute?
