### ISSUE TITLE
Using with server side rendering in react and webpack tree shaking

### ISSUE THREAD

**Issue by davidfurlong** [FortAwesome/react-fontawesome#26]
The server side rendering docs (https://fontawesome.com/how-to-use/server-side-rendering) don't seem particularly relevant to when using with react server rendering. Any ideas on how to do this?

**Comment by stephen-last** [comment]
I think we submitted the same issue at the same time. Mine is in a little bit more detail: https://github.com/FortAwesome/react-fontawesome/issues/27

Do you want to close this issue and subscribe to mine..?

**Comment by davidfurlong** [comment]
closing mine https://github.com/FortAwesome/react-fontawesome/issues/27
