### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by mikefili** [FortAwesome/react-fontawesome#264]
**Describe the bug**
Throughout near all of your README file, there is a typo present in all npm install commands. I count 44 instances.

**Reproducible test case**
View README file

**Expected behavior**
Currently: 
`$ npm i --save @fortawesome/fontawesome-svg-core`
`$ npm i --save @fortawesome/free-solid-svg-icons`
`$ npm i --save @fortawesome/react-fontawesome`

Expected: 
`$ npm i --save @fontawesome/fontawesome-svg-core`
`$ npm i --save @fontawesome/free-solid-svg-icons`
`$ npm i --save @fontawesome/react-fontawesome`

**Desktop (please complete the following information):**

- N/A
- N/A

**Additional context**
N/A

**Comment by elramus** [comment]
I was a bit confused by this too at first, but not a typo :) https://fortawesome.com/
