### ISSUE TITLE
Server-rendering + webpack... styles?

### ISSUE THREAD

**Issue by stephen-last** [FortAwesome/react-fontawesome#27]
I'm using React server-rendering and webpack, which works, however the CSS isn't server rendered.

I've looked at this page: https://fontawesome.com/how-to-use/server-side-rendering, however it's not clear to me how to get the CSS from `@fortawesome/fontawesome` to be picked up by webpack and included in my CSS bundle. 

I also need to stop the inserting of the `<style>` tag in the `<head>` by the client-side `fontawesome` js.

Server-rendering with js disabled in the browser means no CSS for font awesome (the base styles), so I'm seeing this:

> If the CSS is missing when this icon displays in the browser it will flash from a very large icon down to a properly sized one a moment later.

Are there any solutions for this..?

**Comment by davidfurlong** [comment]
my issue is a duplicate it seems.

**Comment by stephen-last** [comment]
Yep, I commented on yours...

I'm looking into this: https://fontawesome.com/how-to-use/font-awesome-api

This seems to work to stop the `<style>` tag being added.

```js
fontawesome.config = {
  autoAddCss: false
}
```

Still trying to get the base styles into my bundle.

**Comment by davidfurlong** [comment]
@stephen-last 
I think the solution lies here:

```
fontawesome.dom.css()

Generates the accompanying CSS that is necessary to correctly display icons. If you choose to disable autoAddCss in the configuration you’ll need to grab these styles and insert them manually into the DOM.
````

**Comment by davidfurlong** [comment]
The css added may be dynamic => in your server render we need to call fontawesome.dom.css() and insert it into the head.

**Comment by stephen-last** [comment]
I was just looking at `fontawesome.dom.css()`.

I've added it but no CSS is added to the bundle.

**Comment by davidfurlong** [comment]
> I've added it but no CSS is added to the bundle.

I don't think thats ever going to happen. Probably easiest to inline this css in the <head></head>

**Comment by davidfurlong** [comment]
For reference, here is the `dom.css()` method, which does do some dynamic stuff

```js
var css = function () {
  var dfp = DEFAULT_FAMILY_PREFIX;
  var drc = DEFAULT_REPLACEMENT_CLASS;
  var fp = config.familyPrefix;
  var rc = config.replacementClass;
  var s = baseStyles;

  if (fp !== dfp || rc !== drc) {
    var dPatt = new RegExp('\\.' + dfp + '\\-', 'g');
    var rPatt = new RegExp('\\.' + drc, 'g');

    s = s.replace(dPatt, '.' + fp + '-').replace(rPatt, '.' + rc);
  }

  return s;
};
```

**Comment by stephen-last** [comment]
I've got this working...

```js
import fontawesome from '@fortawesome/fontawesome'
import { OriginalSource } from 'webpack-sources'

class FontAwesome {
  apply (compiler) {
    compiler.plugin('compilation', (compilation) => {
      compilation.plugin('additional-assets', (callback) => {
        compilation.assets['css/fontawesome.css'] = new OriginalSource(
          fontawesome.dom.css(),
          'fontawesome.css'
        )
        callback()
      })
    })
  }
}

export default FontAwesome
```

It spits out a new CSS file with the FA base styles.

Going to see if I can add to the CSS asset I already create, rather than create a new asset. I'll keep posting here with what I have.

**Comment by stephen-last** [comment]
`compilation.assets['css/fontawesome.css'] = new RawSource(fontawesome.dom.css())`

Also works...

**Comment by stephen-last** [comment]
I've asked for help here: https://stackoverflow.com/questions/47714048/webpack-insert-add-new-css-to-the-bundle

**Comment by robmadole** [comment]
In the latest release of `@fortawesome/fontawesome` we've included the CSS for this as an external file. The packages.json points to it with the `style` property. I think the postcss plugins will use this value. Let me know if that helps.

**Comment by davidfurlong** [comment]
@stephen-last I think we can close this issue thanks @robmadole
