### ISSUE TITLE
FontAwesome component should accept rotation 0.

### ISSUE THREAD

**Issue by ViktorKorladinov** [FortAwesome/react-fontawesome#278]
If you have a let's say a button with an Icon and text in it, if you want to rotate the icon by 180 degrees every time it's pressed, it should be possible to just set the rotation prop to 0/180 respectively, however currently the only allowed numbers are 0,180 and 270. It would be a lot cleaner if the logic for rotation={0} would be inside the component.
![image](https://user-images.githubusercontent.com/40514684/64014256-fd90df00-cb21-11e9-9c70-71995f7b81e5.png)

**Comment by robmadole** [comment]
@ViktorKorladinov agreed. I'd accept and merge a PR for this :+1:
