### ISSUE TITLE
Adding "fab" not working

### ISSUE THREAD

**Issue by abrown945** [FortAwesome/react-fontawesome#281]
I am getting the following error with my React App in the console accompanied by the absence of rendered icons. 

![Screenshot (32)](https://user-images.githubusercontent.com/23192489/64459456-e9bb1f00-d0c5-11e9-997e-5dff908c999a.png)

As far as I am aware, I am doing everything correctly after viewing the documentation several times. 

I am importing a list of the icon names and the image displays that they are being successfully imported name wise.

This is what I am doing with the imported names

`    const icons = iconList.map((iconImg) => {
        return (
            <FontAwesomeIcon icon={['fab', iconImg]} />
        )
    });`

As you can see, I already include the prefix 'fab'. I also made sure to install the npm package for the free brand names. I'm not sure what to do next.

I am using this `icons` object later in the app as well, so not issue there. I realize that I need a key for each icon, but I will handle that once I get them to show up

**Comment by abrown945** [comment]
My regular fontawesome icons are working just fine as well, so I believe the issue is specifically with brand icons

**Comment by AarRidho** [comment]
According to the docs (README), you need to import 'fab' in your app.js

> However, the "apple", "microsoft", and "google" brand icons live in the package @fortawesome/free-brands-svg-icons. So we need to specify a different prefix for them—not the default fas, but fab, for Font Awesome Brand.

**Comment by abrown945** [comment]
I imported fab beforehand and it didn't work so I tried to write it in explicitly as shown in the documentation to no avail.

I ended up adding it directly to the library in the index.js file. I'm not sure why that worked but I can't import "fab" on its on.
