### ISSUE TITLE
Null classes showing up on svg in 0.1.5

### ISSUE THREAD

**Issue by MrSauceman** [FortAwesome/react-fontawesome#289]
With the latest release, css classes like ‘fa-null’ and ‘fa-rotate-null’ are showing up on the svg element.

I created a small project that reproduces this behavior:  https://codesandbox.io/s/eloquent-framework-ipyx9

Just inspect the icon in dev tools and check the classes on the svg element.

This does not happen in v0.1.4.

**Comment by robmadole** [comment]
0.1.6 released that should resolve this. Let us know if it's not working as expected!

**Comment by collinpage** [comment]
Not sure if this is related but I get these classes from SSR:
fa-rotate-null
fa-pull-null

It only seems to do this with the fa-sign-in icon (https://fontawesome.com/icons/sign-in?style=regular).

This happens with 0.1.6 and 0.1.7.

if I downgrade to 0.1.5, I don't get the error from font awesome but I get a similar error with the sub-menu icon from ant design (really strange).

**Comment by robmadole** [comment]
@collinpage could you perhaps provide a reproducible test case?
