### ISSUE TITLE
Module not found: Can't resolve '@fortawesome/pro-duotone-svg-icons' error

### ISSUE THREAD

**Issue by gokuu** [FortAwesome/react-fontawesome#295]
**Describe the bug**
I have a strange error in my project. I'm using React, and Typescript. I also have a Pro license, and, with this `package.json`:
```
{
  (...),
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.17",
    "@fortawesome/free-brands-svg-icons": "^5.11.2",
    "@fortawesome/free-regular-svg-icons": "^5.11.2",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@fortawesome/pro-duotone-svg-icons": "^5.11.2",
    "@fortawesome/pro-light-svg-icons": "^5.11.2",
    "@fortawesome/pro-solid-svg-icons": "^5.11.2",
    "@fortawesome/react-fontawesome": "^0.1.6",
    "@material-ui/core": "^3.9.3",
    "@material-ui/icons": "^3.0.2",
    "classnames": "^2.2.6",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "react-scripts": "3.2.0"
  },
  "devDependencies": {
    "@fortawesome/fontawesome-pro": "^5.11.2",
    "@types/classnames": "^2.2.7",
    "@types/node": "*",
    "@types/react": "^16.8.13",
    "@types/react-dom": "*",
    "@types/react-router-dom": "^5.1.0",
    "@typescript-eslint/eslint-plugin": "^2.4.0",
    "@typescript-eslint/parser": "^2.4.0",
    "eslint-plugin-react": "^7.12.4",
    "typescript": "latest"
  },
 (...)
}
```

I am able to import icons from `@fortawesome/pro-solid-svg-icons` and `@fortawesome/pro-light-svg-icons`, but not from `@fortawesome/pro-duotone-svg-icons`, and `@fortawesome/pro-regular-svg-icons`.

The two latter raise a `Module not found: Can't resolve ...` error.

**Reproducible test case**
If needed, I'll try to create a fiddle with this.

**Expected behavior**
I was expecting to be able to `import` all the icons.

**Desktop (please complete the following information):**

- Browser (Not applicable)
- Version (Not applicable)

**Additional context**

**Comment by robmadole** [comment]
Yeah, go ahead and provide a reproducible test case. Nothing is jumping out at me right away.

**Comment by gokuu** [comment]
I'm closing this. I've finally been able to get back to the project I was working on, and this doesn't happen anymore... 

If it comes back, I'll reopen it. 

Sorry for wasting your time 😊
