### ISSUE TITLE
Update README.md to specify including @fortawesome/fontawesome-free-solid

### ISSUE THREAD

**Issue by bjonesy** [FortAwesome/react-fontawesome#30]
Install instructions specify to only install two packages which are 
```
$ yarn add @fortawesome/fontawesome
$ yarn add @fortawesome/react-fontawesome
```
Should make it more clear that if you want to only import specific icons then you need to also include 
```
$ yarn add @fortawesome/fontawesome-free-solid
```
I'm sure it could be assumed, that this might be obvious, but in my opinion it would be better documentation to clearly define that.

**Comment by bjonesy** [comment]
I see that most of the information needed is located here https://fontawesome.com/how-to-use/font-awesome-api.  Maybe including a link to this would be helpful and avoid issue requests like this one.

**Comment by mlwilkerson** [comment]
I submitted a significant revision of the doc, which includes the guidance about installing @fortawesome/fontawesome-free-solid.

@bjonesy would you care to have a look at this revision? Comments welcome.
https://github.com/FortAwesome/react-fontawesome/blob/b604df20fff417049d7829a3621c4567e98e4982/README.md

**Comment by bjonesy** [comment]
@mlwilkerson Thanks for updating!.  I appreciate it.  Also wanted to say great work on V5.  Thanks again.
