### ISSUE TITLE
fa-star-o seems to be missing from @fortawesome/free-solid-svg-icons

### ISSUE THREAD

**Issue by lomse** [FortAwesome/react-fontawesome#305]
**Is your feature request related to a problem? Please describe.**
fa-star-o icon seems to be missing from `@fortawesome/free-solid-svg-icons`.  I can find what is listed below though:

- faStar
- faStarAndCrescent
- faStarHalf
- faStarHalfAlt

**Describe the solution you'd like**
Maybe something like `faStarO` or `faStarEmpty` would be great.

**Describe alternatives you've considered**

**Additional context**

**Comment by robmadole** [comment]
Hi @lomse . The outline version is available in `@fortawesome/free-regular-svg-icons`

**Comment by lomse** [comment]
nice one.

**Comment by ankush1401** [comment]
Hi did you manage to find it? @lomse I've checked `@fortawesome/free-regular-svg-icons` but i can't see the outline version in there.

**Comment by awaisdar001** [comment]
Same here, can't seem to find it.

**Comment by robmadole** [comment]
The `-o` postfix is no longer needed. You can import it like this:

```javascript
import { faStar } from '@fortawesome/free-regular-svg-icons'
```
