### ISSUE TITLE
@fortawesome/react-fontawesome@0.1.7' is not in the npm registry.

### ISSUE THREAD

**Issue by Floriferous** [FortAwesome/react-fontawesome#307]
npm install fails because apparently the package can't be found, I believe we already had this issue not too long ago.

The full error is this:

```sh
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.fontawesome.com/REDACTED/@fortawesome/react-fontawesome/-/react-fontawesome-0.1.7.tgz
npm ERR! 404 
npm ERR! 404  '@fortawesome/react-fontawesome@0.1.7' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-12-06T13_59_06_079Z-debug.log

Exited with code exit status 1
```

What is going on?

**Comment by robmadole** [comment]
@Floriferous please send us an email at [hello@fontawese.com](mailto:hello@fontawesome.com). You accidentally leaked your NPM token in this comment and we'll need to reset it.

I'll help you resolve the missing package and walk you through the token reset.

**Comment by Floriferous** [comment]
Ha sorry about that, just sent you an email.
