### ISSUE TITLE
FontAwesomeIconProps type does not include swapOpacity (react component)

### ISSUE THREAD

**Issue by Toonshorty** [FortAwesome/react-fontawesome#308]
The documentation at https://www.npmjs.com/package/@fortawesome/react-fontawesome#features indicates that the property `swapOpacity` can be used for duotone icons.

However, the current React package (0.1.7) does not include this property in the `FontAwesomeIconProps` type and so the compiler will error.

**Comment by robmadole** [comment]
@Toonshorty I just released 0.1.8. Can you give this another try?
