### ISSUE TITLE
Not in the npm registry

### ISSUE THREAD

**Issue by jokokoloko** [FortAwesome/react-fontawesome#312]
I am getting this error when trying to update my packages within a Gatsby project:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.fontawesome.com/XXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/@fortawesome%2freact-fontawesome
npm ERR! 404 
npm ERR! 404  '@fortawesome/react-fontawesome@^0.1.7' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

This also appears for the latest versions and for other packages such as @fortawesome/fontawesome-svg-core

**Comment by hamiltonchua** [comment]
Hello, I'm getting the same error. I am unable to install via npm or yarn. It seems all your packages have been removed from the npm registry.

**Comment by jokokoloko** [comment]
Any updates with this?

**Comment by hamiltonchua** [comment]
hello @jokokoloko, I figured it out. 

Do you have a .npmrc file ? 

What worked for me was to change it to something like

`@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}`

where FONTAWESOME_NPM_AUTH_TOKEN is the environment variable with your authorization token.

ALSO and very important, you should remove your code snippet about because it's exposing your fontawesome auth token.

**Comment by robmadole** [comment]
@jokokoloko please see the updated documentation on package managers.

https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro

Once you update your `.npmrc` file make sure you remove the `package-lock.json` or `yarn.lock` to reset your URLs.

**Comment by robmadole** [comment]
Oh and yes, as @hamiltonchua said you have exposed your private token. So head to https://fontawesome.com/account and cycle your token.

(I've edited your post to remove the reference to your token)

**Comment by dark-swordsman** [comment]
@robmadole Sorry for messaging on a closed issue, but I'm a little confused here.

When you install `react-fontawesome` or `free-solid-svg-icons`, it doesn't require the token, but for svgcore, it does.

Even though there is a free set of icons, do you still need to make an account or something for the svg core? This isn't very clear in any documentation that I can find, and the one you provided only mentioned a token for Pro icons.

**Comment by robmadole** [comment]
@dark-swordsman the `@fortawesome/fontawesome-svg-core` package does not require a token. It's available through `registry.npmjs.com` like most packages. Here is the package link: https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core

Perhaps you have a misconfiguration in your package-lock.json or yarn.lock?

**Comment by dark-swordsman** [comment]
I don't see any odd configuration or issues inside the `package.json`. I was getting this issue:

```
$ npm i --save @fortawesome/fontawesone-svg-core
npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "--save" "@fortawesome/fontawesone-svg-core"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Not found : @fortawesome/fontawesone-svg-core
npm ERR! 404
npm ERR! 404  '@fortawesome/fontawesone-svg-core' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxx/projects/xxx/npm-debug.log
```

Creating an `.npmrc` file with `@fortawesome:registry=https://npm.fontawesome.com/` inside it causes this:

```
$ npm i --save @fortawesome/fontawesone-svg-core
npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "--save" "@fortawesome/fontawesone-svg-core"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code E401

npm ERR! authentication required : @fortawesome/fontawesone-svg-core
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xxx/projects/xxx/npm-debug.log
```

By the way, this is a small project that I'm helping someone with, so I'm not fully versed with the code base. They used `create-react-app` from the looks of it. Let me know if there's anything to check. 

Also, this is using WSL Ubuntu.

Here's the package.json:

```
{
  "name": "[redacted]",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fortawesome/free-regular-svg-icons": "^5.12.0",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@fortawesome/react-fontawesome": "^0.1.8",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.4.0",
    "@testing-library/user-event": "^7.2.1",
    "bootstrap": "^4.4.1",
    "node-sass": "^4.13.1",
    "react": "^16.12.0",
    "react-accessible-accordion": "^3.0.1",
    "react-animations": "^1.0.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-dom": "^16.12.0",
    "react-live-clock": "^3.1.0",
    "react-rounded-image": "^2.0.2",
    "react-scripts": "3.3.0",
    "react-scroll-up-button": "^1.6.4",
    "react-social-icons": "^4.1.0",
    "react-typical": "^0.1.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Comment by elramus** [comment]
@dark-swordsman Looks like a typo maybe? "awesone" instead of "awesome"? `@fortawesome/fontawesone-svg-core`

**Comment by dark-swordsman** [comment]
I definitely did have a typo, but still getting the same error:

```
$ npm i --save @fortawesome/fontawesome-svg-core
npm ERR! Linux 4.4.0-18362-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "--save" "@fortawesome/fontawesome-svg-core"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code E401

npm ERR! authentication required : @fortawesome/fontawesome-svg-core
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/junninho/projects/BChack/npm-debug.log
```

**Comment by kavykun** [comment]
I still get this occasionally

**Comment by mdodge-ecgrow** [comment]
> Once you update your `.npmrc` file make sure you remove the `package-lock.json` or `yarn.lock` to reset your URLs.

You should definitely add this line to the docs.  It took me way too long of trial and error and googling before I finally found that answer and it solved my problem.  May be obvious to some, but definitely not me.
