### ISSUE TITLE
402 Payment Required on build

### ISSUE THREAD

**Issue by stevensacks** [FortAwesome/react-fontawesome#315]
**Describe the bug**
Our build process just started failing out of nowhere.

```bash
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-solid-svg-icons/-/5.12.0/pro-solid-svg-icons-5.12.0.tgz: Request failed \"402 Payment Required\""
```

**Expected behavior**
This bug literally just started happening on our CI today on a project that we've been working on for years. Our account is current and up to date. Our next payment isn't due until October, 2020. 

This has to be a bug.

**Comment by dschwank** [comment]
Same here - all licenses have the same issue and are all valid.

**Comment by stevensacks** [comment]
This too
```error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-svg-core/-/1.2.26/fontawesome-svg-core-1.2.26.tgz: Request failed \"402 Payment Required\"".```

**Comment by ybiquitous** [comment]
Me too. We cannot deploy... 🙏 🙏 🙏 😭 😭 😭

**Comment by Kocal** [comment]
Same here... I can download Pro version on https://fontawesome.com/download but not with npm/yarn :sweat_smile:

**Comment by saidziani** [comment]
Same issue. 
`npm ERR! 402 Payment Required`

**Comment by simonb-has** [comment]
same here ...

**Comment by robmadole** [comment]
All, we are very sorry. We had a misconfiguration with our service provider that manifested as the `402 Payment Required`. We didn't have any monitoring to detect this particular problem so it fell through the cracks.

We've corrected it and everything should be back up and running.

**Comment by herbola** [comment]
Still an issue?
