### ISSUE TITLE
Attempted import error: 'faThermometerHigh' is not exported from '@fortawesome/free-solid-svg-icons'

### ISSUE THREAD

**Issue by TomlDev** [FortAwesome/react-fontawesome#317]
Hey everyone, firstly thanks for this awesome icon package and the great documentation!
**Describe the bug**
The bug: Im using react, and the following (free) FA packages:
```
    "@fortawesome/fontawesome-svg-core": "^1.2.26",
    "@fortawesome/free-brands-svg-icons": "^5.12.0",
    "@fortawesome/free-regular-svg-icons": "^5.12.0",
    "@fortawesome/free-solid-svg-icons": "^5.12.0",
    "@fortawesome/react-fontawesome": "^0.1.8",
```
And the following error:

> Attempted import error: 'faThermometerHigh' is not exported from '@fortawesome/free-solid-svg-icons'

despite it was updated and **is** included in ^5.5.0

**Reproducible test case**
`    "react": "^16.12.0"`
and FA dependencies as state above, then

`import { faStar, faThermometerHigh} from '@fortawesome/free-solid-svg-icons'`

**Expected behavior**
When trying to import faThermometerHigh compiler says its not exported from the solid package, while other faIcons work

Thanks in advance

**Comment by robmadole** [comment]
@TomlDev are you wanting this instead? https://fontawesome.com/icons/temperature-high?style=solid

Or this? https://fontawesome.com/icons/thermometer-full?style=light

**Comment by TomlDev** [comment]
Alright, just a typo. Thanks for the hint, can be closed.
