### ISSUE TITLE
Missing id attribute in typescript declarations

### ISSUE THREAD

**Issue by rodlukas** [FortAwesome/react-fontawesome#324]
**Describe the bug**
Typescript interface `FontAwesomeIconProps` does not include `id` attribute. Althought the `id` attribute is correctly emmited by `FontAwesomeIcon` in real when used.

**Reproducible test case**
Not neccessary - open file https://github.com/FortAwesome/react-fontawesome/blob/master/index.d.ts, interface `FontAwesomeIconProps`.

**Expected behavior**
Typescript interface `FontAwesomeIconProps` should include the `id` attribute:
```ts
id?: string
```

**Comment by robmadole** [comment]
@rodlukas I don't think that this component is emitting `id`. Can you provide a reproducible example so we can see what's going on? (Also the `FontAwesomeIconProps` are the _input_ to the component–not the output)

**Comment by robmadole** [comment]
I'll re-open this one if I'm missing the point of your ticket.

**Comment by rodlukas** [comment]
@robmadole here's the sandbox: https://codesandbox.io/s/intelligent-murdock-o2bt9?eslint=1&fontsize=14&hidenavigation=1&theme=dark

`id` prop is set on `FontAwesomeIcon` to *testID*, this value is then emitted to the `svg` element in the DOM, but as you can see, the linter is yelling about missing id attribute in `FontAwesomeIconProps`.
The only workaround is wrapping the `FontAwesomeIcon` with `span` with `id`, but only because of the linter, because the `id` is already there even without this workaround.

![2020-02-27 (1)](https://user-images.githubusercontent.com/13161588/75433010-99739a00-594f-11ea-8163-307d07adc71f.png)

**Comment by robmadole** [comment]
Gotcha. [Here is the TypeScript definition file](https://github.com/FortAwesome/react-fontawesome/blob/master/index.d.ts). We don't use TS so I have no idea how it should be changed to support the `id` property. Can you recommend a change?

**Comment by rodlukas** [comment]
@robmadole here's the PR - https://github.com/FortAwesome/react-fontawesome/pull/326. 
The `id` attribute is practically the same as ie. `className` attribute in the TS file.

**Comment by robmadole** [comment]
PR merged. Thanks a bunch @rodlukas !
