### ISSUE TITLE
FontAwesome Duotone add custom primary and secondary color like Font Awesome origin library

### ISSUE THREAD

**Issue by cristianManrique** [FortAwesome/react-fontawesome#325]
**Describe the bug**
In the Original Font Awesome library, we can define custom colors for fa-primary and fa-secondary colors. Also, we can define custom the opacity for the booth.

`<i class="fad fa-french-fries" style="--fa-primary-color: red; --fa-secondary-color: gold; --fa-secondary-opacity: **1.0"**></i>`

**Expected behavior**
Ad new props to define a custom primary, a secondary color, and opacity.

**Suggestion**
`import { faSquare as faSquareDuo } from "@fortawesome/pro-duotone-svg-icons/faSquare";
<FontAwesomeIcon
        icon={faSquareDuo}
         faPrimary="custom class"
         faSecondary="custom class"
         faPrimaryOpacity={0.3}
         faSecondaryOpacity={1}
 />`

[https://blog.fontawesome.com/introducing-duotone/](url)

**Comment by cristianManrique** [comment]
![2020-02-25 15_14_27-Window](https://user-images.githubusercontent.com/16122298/75283840-96f33200-57e1-11ea-895f-2bb938c14b29.png)

**Comment by robmadole** [comment]
@cristianManrique since these properties are just CSS Custom Properties you can use React's `style` property or style the components as you would normally with CSS. If I missed your meaning let me know and I can re-open this ticket.

**Comment by cristianManrique** [comment]
@robmadole 
Thanks for your answer but style is a CSS hardcoded.  I witch I can add dynamic material-ui css classes.

maybe something like
` style = (theme) => {
FirstCustom: {
 color: "yellow"
},
SecondCustom:{
 color: "red"
}
}`
`<FontAwesomeIcon icon={faSquareDuo} style = {{
 faPrimary : classes.FirstCustom,
 faSecondary : classes.secondCustom,
faPrimaryOpacity: 0.3, 
faSecondaryOpacity: 1,
}} />`

or can you please give show a exemple

**Comment by cristianManrique** [comment]
Please re-open it

**Comment by robmadole** [comment]
Here's an example: https://codesandbox.io/s/duotone-icons-n79s1

**Comment by cristianManrique** [comment]
@robmadole Tks ! Have nice day ! 😃
