### ISSUE TITLE
Unable to find and add `beaker` icon

### ISSUE THREAD

**Issue by arunkumar741** [FortAwesome/react-fontawesome#327]
**Describe the bug**
I am unable to add the beaker icon in react-awesome

**Reproducible test case**
[https://fontawesome.com/v3.2.1/icon/beaker](url)

**Expected behavior**
i tried to access beaker using this code, but there is no icon in the library

**Desktop (please complete the following information):**

- Version

`import { library } from "@fortawesome/fontawesome-svg-core";`
`import { fab } from "@fortawesome/free-brands-svg-icons";`
`import {`
 ` faCoffee,`
`  faDesktop,`
  `faBriefcase`
`} from "@fortawesome/free-solid-svg-icons";`
`import App from "./components/App";`

`library.add(fab, faDesktop, faCoffee, faBriefcase);`

**Comment by robmadole** [comment]
@arunkumar741 this component uses Font Awesome 5.

Try https://fontawesome.com/icons/flask?style=solid
