### ISSUE TITLE
External loading doesn't work

### ISSUE THREAD

**Issue by MekliCZ** [FortAwesome/react-fontawesome#34]
Hello,
I'm having problems with externally loaded FA from CDN. Icons just don't appear. I also tried it on clean create-react-app.
I'm using CDN: `<script defer src="https://use.fontawesome.com/releases/v5.0.1/js/all.js"></script>` which is properly loaded by browser and when I edit DOM manually and type `<i class="fa fa-coffee"></i>` somewhere, it works and the icon appears.
The script looks like this:
```jsx
import React, { Component } from 'react';
import FontAwesomeIcon from '@fortawesome/react-fontawesome'
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title"><FontAwesomeIcon icon="coffee" /></h1>
        </header>
      </div>
    );
  }
}

export default App;
```

**Comment by robmadole** [comment]
We'll get this resolved soon. We have the work complete on this just needs a bit more testing.

**Comment by robmadole** [comment]
@MekliCZ please upgrade `@fortawesome/fontawesome` and `@fortawesome/react-fontawesome` and then take another look at the docs and the examples (they've been updated). The couple of things you need to do:

1. Install and import one of the styles `import solid from '@fortawesome/fontawesome-free-solid'`
1. Add it to your library with `fontawesome.library.add(solid)`

**Comment by yocmen** [comment]
so if we have imported the fontawesome-all.js with a script tag on the head, we need to reimport the icons? im using the pro version and i get the same result (no icon) importing the js on the head and then in the component my react-fontawesome.

**Comment by alerizzo** [comment]
Sorry @robmadole  but, I'm having the same issue, and I don't want to import icons, because I'm building a library and the components will receive just the name of the icon. It is not the case @MekliCZ is describing, which is the External Loading option in the Usage section of the Readme. 

First load, no icons. Next component renders, everything's ok. This should be reopened.

**Comment by robmadole** [comment]
Ah ok @alerizzo. If it's not the case that @MekliCZ is describing can you provide a reproducible test case that illustrates the issue?

**Comment by alerizzo** [comment]
Sure. 

1- Create a new react APP
```
npx create-react-app test-fa
```

2 - Add React FontAwesome
```
cd test-fa
npm i --save @fortawesome/fontawesome
npm i --save @fortawesome/react-fontawesome
```

3 - Start app
```
npm start
```


4 - Add FontAwesome reference in public\index.html
```
<script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
```


5 - Import FontAwesome in App.js
```
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
```


6 - Add an icon (wherever you want) in App.js
```
<FontAwesomeIcon icon="coffee" />
```

7 -  If you visit localhost:3000, there's no icon. That's the bug.

8 - Now, for the sake of science, let's make a change to the state 5 seconds after the component is mounted
```
  constructor(props) {
    super(props);

    this.state = { dummy: false };
  }

  componentDidMount() {
    setTimeout( () => { this.setState({ dummy: true }) }, 5000 );
  }
```

9 - Refresh again, no icon.... Count til' 5.... and there it is

**Comment by robmadole** [comment]
Ok, after a lot of work on these components over the past month we are headed towards a scenario where we are probably not going to support the "external" example. This is a complicated use case prone to all sorts of problems.

Our current recommendation is to use NPM to install icon content packages and to use a tool such as Webpack or Rollup to bundle just the icons that should be used.

@alerizzo this should not impact your component's ability to work. You can still skip loading any icons but you'll have to have your users follow the instructions for using the library. Check the docs here: https://github.com/FortAwesome/react-fontawesome/tree/development
