### ISSUE TITLE
Unable to vertically align icon using custom class, but works with style tag

### ISSUE THREAD

**Issue by fgs-dbudwin** [FortAwesome/react-fontawesome#340]
**Describe the bug**
When I create an icon like the following, it will display as expected where the icon is the expected size and vertically aligned in the middle:

`<FontAwesomeIcon icon="coffee" style={{fontSize: "1.75em", verticalAlign: "middle"}} />`

However, when I switch it to work like the following...

```
.custom-icon {
    font-size: 1.75em;
    vertical-align: "middle";
}
```
```
<FontAwesomeIcon icon="coffee" className="custom-icon" />
```
...the icon will be the correct size (proving it can locate the `custom-icon` class), but will *not* be aligned vertically despite these two methods seeming to be equivalent.

**Reproducible test case**
https://codesandbox.io/s/condescending-flower-o13dn?file=/src/App.js

**Expected behavior**
When applying a custom `class` or a custom `style`, I expect the rendering to behave the same way when both the `class` and `style` have the same CSS applied to it.

**Desktop (please complete the following information):**

Firefox 76.0.1

**Additional context**
N/A

**Comment by robmadole** [comment]
@fgs-dbudwin the icons have a `vertical-align` of `-0.125em` by default and not `middle`. So I think your expectation may be off here?

**Comment by fgs-dbudwin** [comment]
What I'm confused about is in my code sandbox, I display 3 icons.  The first with no CSS formatting, while the second and third icons have identical CSS formatting applied to them but appear different and I'm unsure as to why that is.  I'm trying to determine why applying formatting using a `style` versus a `className` is having a different effect when I expect it to be the same.

**Comment by robmadole** [comment]
Oh, I've gotten caught by this before when going back and forth in CSS vs CSS-in-JS :)

```css
.custom-icon {
  font-size: 1.75em;
  vertical-align: "middle";
}
```

to

```css
.custom-icon {
  font-size: 1.75em;
  vertical-align: middle;
}
```

**Comment by fgs-dbudwin** [comment]
Wow, it was one of those days for me I suppose 🤦 Thank you!
