### ISSUE TITLE
Use pro icon

### ISSUE THREAD

**Issue by bjd-s** [FortAwesome/react-fontawesome#342]
**Describe the bug**
**ON REACTJS**

When i use
    `<i class="fal fa-folders"></i>`
it works great (means npmrc is good), but when I try
    `<FontAwesomeIcon
        icon="folders"
    />`
it doesn't work

**Reproducible test case**
If you have fontawesome pro sub :
https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
Then 
```
import { library } from '@fortawesome/fontawesome-svg-core'
import { fab } from '@fortawesome/free-brands-svg-icons'
import { faFolders } from '@fortawesome/pro-light-svg-icons'
library.add(fab, faFolders);
```

App.tsx:
`import "./components/fontawesome/Fontawesome";`

Library :
```
import { library } from '@fortawesome/fontawesome-svg-core'
import { fab } from '@fortawesome/free-brands-svg-icons'
`import { faFolders } from '@fortawesome/pro-light-svg-icons'`
library.add(fab, faFolders);
```

Component NavList.tsx:
`import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';`

    `<FontAwesomeIcon
        icon="folders"
    />`

**Expected behavior**
I should see the pro icon folders (light or regular), but there is no icon.

**Desktop (please complete the following information):**
Chrome and Firefox ; both last version

I think maybe my call is wrong
`import { faFolders } from '@fortawesome/pro-light-svg-icons'`

Any idea ? :)

**Comment by robmadole** [comment]
Hi @bjd-s try this

```
<FontAwesomeIcon
    icon={['fal', 'folders']}
/>
```

**Comment by danawoodman** [comment]
I think it would be helpful to explicitly call this out in the docs as it wasn't clear to  me either and hence searching issues and coming here. Created a PR to address in #354
