### ISSUE TITLE
i m getting this error can somebody help me with this?

### ISSUE THREAD

**Issue by sakshi8271** [FortAwesome/react-fontawesome#343]
**Describe the bug**

**Reproducible test case**
Include a URL (codepen.io, jsfiddle.net, Git repository, codesandbox.io, stackblitz.com, etc.) that demonstrates the problem.

**Expected behavior**

**Desktop (please complete the following information):**

- Version

**Additional context**

**Comment by sakshi8271** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/52568938/83184859-b33b9d80-a147-11ea-896e-2edee8dbe991.png)

**Comment by rpbeltran** [comment]
Just check your spelling. You put "@fortawesome" with an r instead of "@fontawesome" with an n at the beginning.

**Comment by robmadole** [comment]
`@fortawesome` is correct.

@sakshi8271 it looks like you don't have the module installed. Have you used your package manager to add it?

**Comment by sakshi8271** [comment]
@robmadole  yes i have installed it

**Comment by robmadole** [comment]
Can you please share an example that reproduces the issue you are seeing?

What we'd recommend is using a site like **[codepen.io](https://codepen.io), [jsfiddle.net](https://jsfiddle.net), [jsbin.com](https://jsbin.com), or [codesandbox.io](https://codesandbox.io)** (which is great if you are dealing with NPM packages).

We'll re-open this issue as soon as you can provide this (we close them to keep the issues queue as manageable as possible).
