### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by gablorquet** [FortAwesome/react-fontawesome#349]
**Describe the bug**
Using the commands listed on the readme for installation with pm, I get the following error : 

```
npm ERR! notarget No matching version found for @fortawesome/fontawesome-common-types@^0.2.28.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@fortawesome/fontawesome-svg-core'
npm ERR! notarget
```

**Reproducible test case**
Simply running the following command generates the error every time
```npm i @fortawesome/fontawesome-svg-core```

**Expected behavior**
That it installs

**Desktop (please complete the following information):**

- NPM v6.11.3
- Node 10.17.0

**Comment by robmadole** [comment]
I can't reproduce this @gablorquet. Can you provide more details? Perhaps a verbose log file?
