### ISSUE TITLE
Can't import Github-Alt Icon

### ISSUE THREAD

**Issue by Prottoy2938** [FortAwesome/react-fontawesome#351]
I'm trying to import this font-awesome icon:  **https://fontawesome.com/icons/github-alt?style=brands** onto my __nextjs__ react project
But there's no icon available on **React Fontawesome** with that name.

<br />

My package version: 
```
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-fontawesome": "^0.1.11",
```

How can I use that Icon?

**Comment by robmadole** [comment]
@Prottoy2938 you're going to need the `@fortawesome/free-brands-svg-icons` dependency.

You can then reference it like this if you are using the `library` contstruct:

```jsx
<FontAwesomeIcon icon={['fab', 'github-alt']} />
```
