### ISSUE TITLE
Can't figure out how to get an icon in pro (also has a dash in it)

### ISSUE THREAD

**Issue by WillPwn4Food** [FortAwesome/react-fontawesome#359]
I've installed every react package listed and got the pro packages too.
I just want to use this icon:
`<i className="fal fa-info-circle"></i>`

I can't figure out how to do that.
What do I require?
What single line do I use to call it? I feel like it should just be: `<FontAwesomeIcon icon={["fal", "info-circle"]} />` but what do I require in my react component to get access to it?

I've got:
`import { infoCircle } from "@fortawesome/pro-light-svg-icons";` Is this where I get it, despite the fact that I'm not actually referencing it based on the example code given? Is there a rule where I replace dashes with this case style??
`import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';` Do I use the pro package somewhere and how instead of this??

It seems like everything is so conflicting and doesn't even mention really how to actually get Pro, which appears to work completely different than everything else maybe?

When I look at the console for my page I get this error:

Could not find icon {prefix: "fal", iconName: "infoCircle"} at FontAwesomeIcon (http://localhost:8000/commons.js:77604:20)
So at least something is happening, but I'm not sure what to do.

Please provide a simple example of how to use pro to get that icon in a React component.

**Comment by robmadole** [comment]
When importing the icon you need to prefix with `fa`:

```javascript
import { faInfoCircle } from "@fortawesome/pro-light-svg-icons"
```

You can then use it in your code:

```jsx
<FontAwesomeIcon icon={faInfoCircle} />
```

If you choose to use the icon library:

```javascript
import { library } from '@fortawesome/fontawesome-svg-core'
import { faInfoCircle } from "@fortawesome/pro-light-svg-icons"

library.add(faInfoCircle)
```

You can then reference the icon by name in your component:

```jsx
<FontAwesomeIcon icon={["fal", "info-circle"]} />
```

**Comment by WillPwn4Food** [comment]
Ah thanks.
I think there was some confusion about library vs non library as well as a few other points missing in the docs. 

This made it work for me (doing non library right now).

Thanks!
- Ivan
