### ISSUE TITLE
SSR support and Fontawesome-pro

### ISSUE THREAD

**Issue by usefksa** [FortAwesome/react-fontawesome#36]
Hello,
How can I use fontawesome-pro icons with this library?
I add the folders (fontawesome-pro-brands,fontawesome-pro-solid) locally inside node_modules but these folders are removed whenever I install a new npm package. 

Also, I noticed it do not support Server Side rendering. Is there any way to do SSR?

Thanks

**Comment by usefksa** [comment]
I fixed the SSR part by copy style.css from @fontawesome directory and make it external CSS.

**Comment by marktron** [comment]
@usefksa The documentation for using the pro versions is here: https://fontawesome.com/how-to-use/use-with-node-js#pro. Just follow the instructions for adding your key (shown on the page) to your NPM config, then you'll be able to run `npm i --save @fortawesome/fontawesome-pro-solid` and have it install properly.

**Comment by usefksa** [comment]
Thanks
It works 👍

**Comment by casoetan** [comment]
@usefksa How did you manage the ssr. Details will be helpful

**Comment by usefksa** [comment]
I tried this but it did not work: https://fontawesome.com/how-to-use/use-with-node-js
The server always telling me: icon not found.

you should do the following:
1. copy style.css from @FontAwesome directory to your CSS file.
2. In your App.js:
```
import fontawesome from '@fortawesome/fontawesome';
fontawesome.config = {
	autoAddCss: false
};
```

3. in your sub comp like Header.js just use icon as normal:

```
import React from 'react';
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
import faEnvelope from '@fortawesome/fontawesome-pro-light/faEnvelope';

class Header extends React.PureComponent {
	render() {
return (
			<div className="header">
<FontAwesomeIcon icon={faEnvelope} /> test
</div>
	);
	}
}

export default Header;
```
