### ISSUE TITLE
Icons do not scale correctly in Safari

### ISSUE THREAD

**Issue by adamalston** [FortAwesome/react-fontawesome#377]
## Describe the bug

I am going to be using the moon icon on the toggle on my website ([adamalston.com](https://www.adamalston.com/)) to describe this issue. The issue happens with the other icons as well but they can be ignored for now.

The icons do not scale in Safari when used as `<FontAwesomeIcon />` components. However, they do scale correctly if I download an svg of the icon from the website ([https://fontawesome.com/icons/moon?style=regular](https://fontawesome.com/icons/moon?style=regular)) and create a component using the svg file.

Code that does not scale: 

```js 
<FontAwesomeIcon icon={["far", "moon"]} style={{ color: "#F1C40F" }} />
```

I created a new file `Moon.js`, downloaded the svg from the website, and created a component out of it:

```js
import React from 'react';

const Moon = () => (
    <svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="moon" class="svg-inline--fa fa-moon fa-w-16" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="#F39C12" d="M279.135 512c78.756 0 150.982-35.804 198.844-94.775 28.27-34.831-2.558-85.722-46.249-77.401-82.348 15.683-158.272-47.268-158.272-130.792 0-48.424 26.06-92.292 67.434-115.836 38.745-22.05 28.999-80.788-15.022-88.919A257.936 257.936 0 0 0 279.135 0c-141.36 0-256 114.575-256 256 0 141.36 114.576 256 256 256zm0-464c12.985 0 25.689 1.201 38.016 3.478-54.76 31.163-91.693 90.042-91.693 157.554 0 113.848 103.641 199.2 215.252 177.944C402.574 433.964 344.366 464 279.135 464c-114.875 0-208-93.125-208-208s93.125-208 208-208z"></path></svg>
);

export default Moon;
```

After importing, I replaced `<FontAwesomeIcon ... />` with `<Moon />`

This icon still did not scale correctly so I removed some of the unnecessary attributes from the svg like `focusable`,`data-prefix`, etc.

```js
import React from 'react';

const Moon = () => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="#F39C12" d="M279.135 512c78.756 0 150.982-35.804 198.844-94.775 28.27-34.831-2.558-85.722-46.249-77.401-82.348 15.683-158.272-47.268-158.272-130.792 0-48.424 26.06-92.292 67.434-115.836 38.745-22.05 28.999-80.788-15.022-88.919A257.936 257.936 0 0 0 279.135 0c-141.36 0-256 114.575-256 256 0 141.36 114.576 256 256 256zm0-464c12.985 0 25.689 1.201 38.016 3.478-54.76 31.163-91.693 90.042-91.693 157.554 0 113.848 103.641 199.2 215.252 177.944C402.574 433.964 344.366 464 279.135 464c-114.875 0-208-93.125-208-208s93.125-208 208-208z"></path></svg>
);

export default Moon;
```

Now the moon scales correctly in Safari. Of note here is that I did not add any extra css to handle the icon.

## Reproducible test case

Go to the current production version of my website in Safari ([adamalston.com](https://www.adamalston.com/)). Pay attention to the moon icon and zoom out. The icon's size is constant no matter the zoom level while everything else on the page changes size. 
| Zoom level | Screenshot |
| ----------- | -----------:  |
| 100% | <img width="90" alt="Screen Shot 2020-09-05 at 4 51 06 AM" src="https://user-images.githubusercontent.com/18297826/92301690-a216df80-ef33-11ea-920d-824cd0658fde.png"> |
| 90% | <img width="80" alt="Screen Shot 2020-09-05 at 4 51 24 AM" src="https://user-images.githubusercontent.com/18297826/92301692-a511d000-ef33-11ea-9b0b-588da2358571.png"> |
| 80% | <img width="70" alt="Screen Shot 2020-09-05 at 4 51 37 AM" src="https://user-images.githubusercontent.com/18297826/92301695-a8a55700-ef33-11ea-8a97-17aca9e18242.png"> |

Now try opening my website in Chrome and/or Firefox. If you zoom out you will see that the icon correctly scales with the zoom level.

## Expected behavior

Here is a staged version of my website with the `<Moon />` component and svg instead of the`<FontAwesomeIcon />` component ([https://5f533fa090670f8e4b5c4324--adamalston.netlify.app/](https://5f533fa090670f8e4b5c4324--adamalston.netlify.app/)). If you open it in Safari and zoom out you will see that the icon scales correctly. It also works in Chrome and Firefox.

| Zoom level | Screenshot |
| ----------- | -----------:  |
| 100% | <img width="90" alt="Screen Shot 2020-09-05 at 4 57 29 AM" src="https://user-images.githubusercontent.com/18297826/92301780-8829cc80-ef34-11ea-9631-8d132a611c3e.png"> |
| 90% | <img width="80" alt="Screen Shot 2020-09-05 at 4 57 54 AM" src="https://user-images.githubusercontent.com/18297826/92301783-8d871700-ef34-11ea-948c-0483a5702f44.png"> |
| 80% | <img width="70" alt="Screen Shot 2020-09-05 at 4 58 07 AM" src="https://user-images.githubusercontent.com/18297826/92301786-92e46180-ef34-11ea-8724-3df471b869fc.png"> |

## Desktop:

- Browser: Safari
- Version: 13.1.2 and 14.0, (Tested on MacOS 10.15.6 and MacOS 11.0 Beta 6)

## Additional context

GitHub repo for my website [https://github.com/adamalston/v2](https://github.com/adamalston/v2)

---

Edit Sept. 8: The current production version of my website ([adamalston.com](https://www.adamalston.com/)) has transitioned to native svg's instead of `<FontAwesomeIcon ... />` components. To gain a correct perspective on the bug, refer to the staged version of my website ([https://5f533fa090670f8e4b5c4324--adamalston.netlify.app/](https://5f533fa090670f8e4b5c4324--adamalston.netlify.app/)) and look at all icons **besides** the moon icon while zooming in and out.

**Comment by robmadole** [comment]
@adamalston this is a bug in Safari. I don't have the link handy but it's been around for awhile.

Have you checked Safari's issues for this?

**Comment by adamalston** [comment]
I have not checked. Where can I check at? @robmadole

**Comment by robmadole** [comment]
You can look on bugs.webkit.org

**Comment by adamalston** [comment]
Thanks, I found a few bug reports. 

[199236](https://bugs.webkit.org/show_bug.cgi?id=199236) is the most specific one I see but there are quite a few issue when searching for [`svg scaling`](https://bugs.webkit.org/buglist.cgi?quicksearch=svg%20scaling).
