### ISSUE TITLE
Icons disappearing on production

### ISSUE THREAD

**Issue by ybelenko** [FortAwesome/react-fontawesome#379]
**Describe the bug**
Works with React dev server, works with production build on my local server. When I upload to remote server - no icons.

**Reproducible test case**
[Production link](https://johndeerilprisma.company)

**Expected behavior**
I would love to see icons in production build on real server.

**Desktop (please complete the following information):**

- All Browsers
- Version
  - @fortawesome/fontawesome-svg-core": "^1.2.30
  - @fortawesome/free-solid-svg-icons": "^5.14.0"
  - @fortawesome/react-fontawesome": "^0.1.11"

**Comment by robmadole** [comment]
@ybelenko looks like you have something going on with `role="img"`. I haven't dug enough to find out what's going on but you might start there.

**Comment by ybelenko** [comment]
I wasn't configured anything, I used example from FontAwesome website related to React without any modification. What is even more weird that if I copy entire svg node in Safari web inspector and paste it anywhere at the same page then icon appears.

Copied svg node looks like:
```html
<svg 
    aria-hidden="true" 
    focusable="false" 
    data-prefix="fas" 
    data-icon="envelope" 
    class="svg-inline--fa fa-envelope fa-w-16 " 
    role="img" 
    xmlns="https://www.w3.org/2000/svg" 
    viewbox="0 0 512 512"
>
    <path 
        fill="currentColor" 
        d="M502.3 190.8c3.9-3.1 9.7-.2 9.7 4.7V400c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V195.6c0-5 5.7-7.8 9.7-4.7 22.4 17.4 52.1 39.5 154.1 113.6 21.1 15.4 56.7 47.8 92.2 47.6 35.7.3 72-32.8 92.3-47.6 102-74.1 131.6-96.3 154-113.7zM256 320c23.2.4 56.6-29.2 73.4-41.4 132.7-96.3 142.8-104.7 173.4-128.7 5.8-4.5 9.2-11.5 9.2-18.9v-19c0-26.5-21.5-48-48-48H48C21.5 64 0 85.5 0 112v19c0 7.4 3.4 14.3 9.2 18.9 30.6 23.9 40.7 32.4 173.4 128.7 16.8 12.2 50.2 41.8 73.4 41.4z"
    >
    </path>
</svg>
```

**Comment by ybelenko** [comment]
@robmadole In your defence, I just installed Octicons icons and they doesn't appear on server too :smile:
I guess it's a problem with SVG itself.

**Comment by robmadole** [comment]
@ybelenko this is not normally a problem. My guess is that some other library you have is doing something funky, maybe accessibility related?

Are you satisfied that it's not `react-fontawesome`? Can I go ahead and close this ticket?

**Comment by ybelenko** [comment]
Yes, I'm closing issue. I changed installation to webfonts import and it works. However my Webpack config is pretty common, don't know why svg disappears.
