### ISSUE TITLE
Deploy on Netlify failing

### ISSUE THREAD

**Issue by piknikki** [FortAwesome/react-fontawesome#388]
**Describe the bug**
After adding the @fortawesome dependencies, then trying to deploy to Netlify (via my github push), it fails, stating that  @fortawesome is not in the npm registry.

**Reproducible test case**
https://github.com/piknikki/vue-socialmedia-dashboard 

**Expected behavior**
I expect the dependencies to be included in the build. The build right before this passed, but my toggle wasn't working correctly.

**Desktop (please complete the following information):**

- Browser: Chrome
- Version 85.0.4183.102

**Additional context**
Error log from Netlify:
11:08:08 AM: Build ready to start
11:08:09 AM: build-image version: b0258b965567defc4a2d7e2f2dec2e00c8f73ad6
11:08:09 AM: build-image tag: v3.4.1
11:08:09 AM: buildbot version: 648208d76731cd5bca75c1e9bc99d2032a1f1473
11:08:10 AM: Fetching cached dependencies
11:08:10 AM: Starting to download cache of 101.0MB
11:08:10 AM: Finished downloading cache in 822.968703ms
11:08:10 AM: Starting to extract cache
11:08:15 AM: Finished extracting cache in 4.126345344s
11:08:15 AM: Finished fetching cache in 4.985952059s
11:08:15 AM: Starting to prepare the repo for build
11:08:15 AM: Preparing Git Reference refs/heads/master
11:08:16 AM: Starting build script
11:08:17 AM: Installing dependencies
11:08:17 AM: Python version set to 2.7
11:08:17 AM: Started restoring cached node version
11:08:20 AM: Finished restoring cached node version
11:08:20 AM: v12.18.0 is already installed.
11:08:21 AM: Now using node v12.18.0 (npm v6.14.4)
11:08:21 AM: Started restoring cached build plugins
11:08:21 AM: Finished restoring cached build plugins
11:08:21 AM: Attempting ruby version 2.7.1, read from environment
11:08:23 AM: Using ruby version 2.7.1
11:08:23 AM: Using PHP version 5.6
11:08:23 AM: 5.2 is already installed.
11:08:23 AM: Using Swift version 5.2
11:08:23 AM: Started restoring cached node modules
11:08:23 AM: Finished restoring cached node modules
11:08:23 AM: Installing NPM modules using NPM version 6.14.4
11:08:33 AM: npm ERR! code E404
11:08:33 AM: npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-light-svg-icons - Not found
11:08:33 AM: npm ERR! 404
11:08:33 AM: npm ERR! 404  '@fortawesome/pro-light-svg-icons@5.14.0' is not in the npm registry.
11:08:33 AM: npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
11:08:33 AM: npm ERR! 404 It was specified as a dependency of 'repo'
11:08:33 AM: npm ERR! 404
11:08:33 AM: npm ERR! 404 Note that you can also install from a
11:08:33 AM: npm ERR! 404 tarball, folder, http url, or git url.
11:08:34 AM: npm ERR! A complete log of this run can be found in:
11:08:34 AM: npm ERR!     /opt/buildhome/.npm/_logs/2020-09-23T17_08_33_780Z-debug.log
11:08:34 AM: Error during NPM install
11:08:34 AM: Error running command: Build script returned non-zero exit code: 1
11:08:34 AM: Failing build: Failed to build site
11:08:34 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1
11:08:35 AM: Finished processing build request in 25.02545277s

**Comment by robmadole** [comment]
Access to the `@fortawesome/pro-light-svg-icons` package requires authentication. We have docs here:

https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers
