### ISSUE TITLE
React font awesome:  the icon mobile-alt is missing 

### ISSUE THREAD

**Issue by JacobGeoGeek** [FortAwesome/react-fontawesome#389]
**Describe the bug**
after reading the [React Font Awesome](https://fontawesome.com/how-to-use/on-the-web/using-with/react), 
I notice that the [Mobile-alt](https://fontawesome.com/icons/mobile-alt?style=solid) does not exist in the package: 
`@fortawesome/free-regular-svg-icons`
ex:
`import { faMobileAlt } from "@fortawesome/free-regular-svg-icons";`

Is there any other way to obtain this icon or I need to install another in order to have this icon ?

**Comment by robmadole** [comment]
@JacobGeoGeek that icon in the Regular style is a Pro icon and requires a paid subscription. The icons in the `free-reguilar-svg-icons` are those icons that were present in version 4 that we didn't want our users to lose access to.

**Comment by JacobGeoGeek** [comment]
@robmadole thanks for the infor after looking at the [Doc](https://fontawesome.com/icons/mobile-alt?style=solid) the `fas` is it free icon ?
Also, is there any document or cheat-sheet that list all the free icons ?

**Comment by robmadole** [comment]
@JacobGeoGeek yep, `fas` is free for that icon. We have little badges that indicate that.

Here's the cheatsheet: https://fontawesome.com/cheatsheet/free

**Comment by JacobGeoGeek** [comment]
Good to know! since I'm using the React package is their a way to use the `fas` for the `mobile-alt` ?
for example: 
`<FontAwesomeIcon icon={["fas", "mobile-alt"]} />`

**Comment by JacobGeoGeek** [comment]
Hi @robmadole, I was wondering if you have any solution related on my previous comment: 

> Good to know that the `fas`i s free! since I'm using the React package, is their a way to use the `fas` for the `mobile-alt` ?
> for example:
> `<FontAwesomeIcon icon={["fas", "mobile-alt"]} />`

**Comment by robmadole** [comment]
@JacobGeoGeek I'm going to close this issue as the original subject is no longer relevant.

Yes, please check the documentation. You can use the solid version of `mobile-alt`.
