### ISSUE TITLE
Error 401 adding @fortawesome/react-fontawesome

### ISSUE THREAD

**Issue by EBKH** [FortAwesome/react-fontawesome#390]
**Describe the bug**
On a **new** app when trying to setup fontAwesome with free icons, npm and yarn respond with:
```nodejs
npm ERR! fetch failed https://npm.fontawesome.com/@fortawesome/react-fontawesome/-/0.1.8/react-fontawesome-0.1.8.tgz
npm WARN retry will retry, error on the last attempt: Error: fetch failed with status code 401 
```

**Reproducible test case**
Any new react app this will happen

**Expected behavior**
To be able to install all not pro packages

**Desktop (please complete the following information):**

- Browser Edge (not related to the browser, tho)
- Version 85.0.564.63 

**Additional context**
This is a new behavior, until recently, I was able to work without issues

**Comment by robmadole** [comment]
@EBKH it looks like you have an `.npmrc` somewhere that is configured to use our private NPM registry. Can you check and see?

**Comment by EBKH** [comment]
Indeed, removing the file the problem was resolved; Thanks, and I'll close this issue.
