### ISSUE TITLE
Critical bug: Last npm versions of this lib don't provide a .js file

### ISSUE THREAD

**Issue by Aarbel** [FortAwesome/react-fontawesome#391]
Got this error while building this week:

``` 
Module not found: Error: Can't resolve '@fortawesome/free-solid-svg-icons' 
```

solved by forcing v `5.14.0`

Looks like last npm distributions of this lib don't provide js files.

**Comment by robmadole** [comment]
? @Aarbel I'm not sure I understand. Are you talking about the `@fortawesome/react-fontawesome` package or the `@fortawesome/free-solid-svg-icons` package?

**Comment by Aarbel** [comment]
the second one

**Comment by robmadole** [comment]
Can you provider a reproducible test case? I'm not seeing any issue with that package.
