### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by orlandovallejos** [FortAwesome/react-fontawesome#409]
I am getting an error when getting the package from npm:

https://npm.fontawesome.com/@fortawesome/pro-solid-svg-icons/-/5.15.2/pro-solid-svg-icons-5.15.2.tgz

The error is 502 bad gateway

> error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/pro-solid-svg-icons/-/5.15.2/pro-solid-svg-icons-5.15.2.tgz: Request failed \"502 Bad Gateway\"".
> info If you think this is a bug, please open a bug report with the information provided in "/opt/atlassian/pipelines/agent/build/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by orlandovallejos** [comment]
ok, it's fixed now.

**Comment by NealEhardt** [comment]
This is happening again today.

>error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-svg-core/-/6.5.1/fontawesome-svg-core-6.5.1.tgz: Request failed \"502 Bad Gateway\"".

**Comment by NealEhardt** [comment]
...and now it's working again :)
