### ISSUE TITLE
<div> cannot appear as a descendant of <p>

### ISSUE THREAD

**Issue by stevensacks** [FortAwesome/react-fontawesome#43]
You can't put a `<FontAwesomeIcon>` component inside of a `<p>` tag because:

```Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.```

**Comment by stevensacks** [comment]
Solution: use an `<i>` tag instead?

**Comment by robmadole** [comment]
@stevensacks we don't generate `<div>` tags. what am I missing?

**Comment by stevensacks** [comment]
Got me, but when I put that component inside a p tag, I get that error.

**Comment by robmadole** [comment]
@stevensacks I've created a sandbox that puts a `FontAwesomeIcon` inside a `<p>` tag. Is this what yours looks like? https://codesandbox.io/s/9l05rn3m5o

**Comment by stevensacks** [comment]
I was using just `icon="whatever"` because I already loaded the cdn file in the html file.

**Comment by robmadole** [comment]
The CDN file is not compatible with React, @stevensacks. Please take another look at the documentation and that sandbox example. If you still have trouble I can re-open this issue.

**Comment by stevensacks** [comment]
I was following the docs:
https://github.com/FortAwesome/react-fontawesome#external-loading

Does this not include all of the icons and not just solid?
https://use.fontawesome.com/releases/v5.0.1/js/all.js

**Comment by robmadole** [comment]
@stevensacks here is another example: https://codesandbox.io/s/vrm2pn8jy

Make sure you've upgraded to the latest versions. I see you are using a `5.0.1` version. We've released new versions of all of our packages to address this very issue.

**Comment by stevensacks** [comment]
I literally changed to FA5 just a couple days ago. So you're confirming this bug *was* an issue but it's been fixed in 5.0.2. Thank you.

**Comment by robmadole** [comment]
Yes it certainly was 🐞
