### ISSUE TITLE
Support server rendering

### ISSUE THREAD

**Issue by jonathanazulay** [FortAwesome/react-fontawesome#44]
When importing the component in a server environment (Meteor) I get this error

    TypeError: Cannot read property 'doScroll' of undefined

**Comment by jonathanazulay** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/11984

Duplicate

**Comment by robmadole** [comment]
I'll get this fixed in the main library when I get back from break (early January-ish).

**Comment by robmadole** [comment]
Going to re-open this @jonathanazulay because I want to make sure that the fix integrates with react-fontawesome too.

**Comment by terrencewwong** [comment]
I'd like this too! If there's anyway I can help let me know!

**Comment by robmadole** [comment]
Should be all fixed up in latest version of ‘@fortawesome/fontawesome’
