### ISSUE TITLE
Unable to resolve dependency when installing for Font Awesome v6

### ISSUE THREAD

**Issue by keihsu** [FortAwesome/react-fontawesome#453]
**Describe the bug**
When following the [V6 documentation](https://fontawesome.com/v6.0/docs/web/use-with/react/#_1-add-svg-core), the installation fails on the last step with:
`npm i --save @fortawesome/react-fontawesome@latest`
Error in console shows:
```
npm ERR! While resolving: project@1.0.0
npm ERR! Found: @fortawesome/fontawesome-svg-core@1.3.0-beta2
npm ERR! node_modules/@fortawesome/fontawesome-svg-core
npm ERR!   @fortawesome/fontawesome-svg-core@"^1.3.0-beta2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @fortawesome/fontawesome-svg-core@"^1.2.32" from @fortawesome/react-fontawesome@0.1.15
npm ERR! node_modules/@fortawesome/react-fontawesome
npm ERR!   @fortawesome/react-fontawesome@"*" from the root project
```

**Comment by robmadole** [comment]
@keihsu what version of `npm` are you running?

**Comment by keihsu** [comment]
I was running 7.22.0 and have just updated it to 7.24.1 and tried reinstalling the packages. No issues now, thanks!
