### ISSUE TITLE
classname css styles not working

### ISSUE THREAD

**Issue by vikasacharya16** [FortAwesome/react-fontawesome#460]
```
<FontAwesomeIcon icon={icon} className='selIconColor'   /> 

.selIconColor {
    fill: red; 
_also tried_
   color: red; 
}
```
But the color is not red for the icon

**Comment by robmadole** [comment]
@vikasacharya16 you'll have to provide a more complete reproducible test case. Something that we can run locally. We're happy to take a look at that point. I'll re-open this issue if you have time to provide that.
