### ISSUE TITLE
401 Unauthorized error during Vercel build using Pro icons

### ISSUE THREAD

**Issue by Isaac-Tait** [FortAwesome/react-fontawesome#463]
**Describe the bug**
I am getting this error message:
`error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/react-fontawesome/-/0.1.16/react-fontawesome-0.1.16.tgz: Request failed \"401 Unauthorized\"".`

I was initially getting this error after doing a global install with my Pro token. I reached out to support about it and they said "global installs are hit or miss" and that I should try the `.npmrc` route laid out [here](https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/using-package-managers).

My repo is pubic though so I do not want my token exposed. So, I added the following to my `.npmrc` file:

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=NPM_RC
```

Then I went and added the pro token to my environmental variables (name is: NPM_RC and the value is my token)

**Reproducible test case**
This is the repo in question: https://github.com/Isaac-Tait/ilovetofish

**Expected behavior**
The Vercel build should not fail...

**Desktop (please complete the following information):**
- Does not matter what browser, this is a "backend" issue

**Additional context**
https://stackoverflow.com/questions/70659269/vercel-deploy-of-my-nextjs-app-with-font-awesome-pro-is-returning-a-401-build-er

**Comment by robmadole** [comment]
Try this:

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=${NPM_RC}
```

**Comment by Isaac-Tait** [comment]
@robmadole That worked! Thank you very much 🥳

**Comment by Isaac-Tait** [comment]
New problem now. When I run `yarn outdated` I get the following error message: 

```
error An unexpected error occurred: "Failed to replace env in config: ${NPM_RC}".
```

Any idea on how to resolve? I tried adding `${NPM_RC}` with the token to my `.env` file but that did not change the error message...
