### ISSUE TITLE
inverse prop is missing, ala "fa-inverse"

### ISSUE THREAD

**Issue by ericlowry** [FortAwesome/react-fontawesome#47]
Hello,

  I am using (and loving) font awesome pro.  I recently started layering icons and I noticed that you are missing an obvious property, "inverse". 

Here is the use case from my project:
```
const NewDatabaseIcon = () => (
  <span className="fa-layers fa-fw">
     <FAI icon={ faDatabase } />
      <FAI icon={ faCircle } transform="shrink-7 right-5 down-5" className="fa-inverse"/>
      <FAI icon={ faPlus } transform="shrink-8 right-5 down-5"/>
  </span>
);
```

![result](https://user-images.githubusercontent.com/8302885/34424071-ebcf4b3c-ebdd-11e7-97fd-2fdaa8d52f9a.png)

Instead of className="fa-inverse", it seems more natural to just use `<FAI icon={faCircle} inverse />`, like you can with "spin", "fixedWidth", etc.

**Comment by NateRadebaugh** [comment]
I have a PR out now will include support for `inverse` like you mentioned. #49

**Comment by robmadole** [comment]
This has been merged into `development`
