### ISSUE TITLE
Using self-hosted icons with this library

### ISSUE THREAD

**Issue by zavan** [FortAwesome/react-fontawesome#481]
I think it's not possible to use self-hosted icons with this library, is that correct? Would this feature be considered?

Could we get files [in this format](https://github.com/FortAwesome/Font-Awesome/tree/5.x/js-packages/%40fortawesome/free-solid-svg-icons) in the pro zip file we download? Then it's just a mater of importing them as usual, right?

**Comment by zavan** [comment]
Related https://github.com/FortAwesome/Font-Awesome/issues/17236

**Comment by zavan** [comment]
Just found out that the files are present in the pro repo, so they can be downloaded and imported locally.

https://github.com/FortAwesome/Font-Awesome-Pro/tree/master/js-packages/%40fortawesome

**Comment by robmadole** [comment]
@zavan yes, you can self-host the packages. We do encourage you to make sure they are protected and not available to the public as that would violate our license.

One quick note, the Font-Awesome-Pro repo is version 5 only. We will not be placing version 6 there.

**Comment by benheymink** [comment]
@robmadole  Appreciate this issue is closed, but I'm trying to do the exact same thing to get the pro icons working on an internal app of ours... how does one go from the downloaded Pro package/s to using them locally in the manner detailed here: https://github.com/FortAwesome/Font-Awesome/issues/17236 (which is exactly how I'd like to use them!)

**Comment by benheymink** [comment]
Actually think I cracked it. Installed pro icons using private NPM registry key, then was able to run `npm pack` from within those locally installed packs to generate .tgz archives of the packages. I could then use these to install locally.
