### ISSUE TITLE
Issue with React Portal ?

### ISSUE THREAD

**Issue by WaSa42** [FortAwesome/react-fontawesome#50]
I'm trying to make a sign in button like in this code:
``` javascript
renderSignInButton() {
        const { credentials, dispatch, profile, t } = this.props;
        const { token } = credentials;

        if (token) {
            if (profile.isFetching) {
                return (
                    <button type="button" disabled>
                        <FontAwesomeIcon icon={faSpinner} spin />
                        {t('form:signIn.state.isFetching')}
                    </button>
                );
            }

            return (
                <button type="button" onClick={() => dispatch(signOut())}>
                    <FontAwesomeIcon icon={faSignOutAlt} />
                    {t('form:signIn.button.signOut')}
                </button>
            );
        }

        return (
            <button type="button">
                <FontAwesomeIcon icon={faSignInAlt} />
                {t('form:signIn.button.default')}
            </button>
        );
    }
```

But when the props are updated and the button is rerendered with a different icon, the code differs from the page:

![image](https://user-images.githubusercontent.com/6498751/34652205-908ba8e6-f3db-11e7-988a-a6f71740d37f.png)

![image](https://user-images.githubusercontent.com/6498751/34652217-a20f12e2-f3db-11e7-82f3-88e2403925a5.png)

You see, the React Dev Tools is showing `faSignOutAlt` and `faSpinner`  icon is displayed on the page.

I'm using React Portal feature to render this button.
Don't know what to do.

**Comment by robmadole** [comment]
Hey @WaSa42 I tried to reproduce this:

https://codesandbox.io/s/2vx611pk2j

Can you help me out? Do you have an example or a place I can see this breaking?

**Comment by WaSa42** [comment]
React Portal is refering to : https://reactjs.org/docs/portals.html

I tried to reproduce at best the current situation:
* My Redux store is updated
* The connected component rerender with another props
* A button with a different icon is rendered depending that prop
* Again the store is updated and again all JSX rerender

Here's the code sandbox : https://codesandbox.io/s/13jmrqxr37
You'll see that the icon is updated to the spinner at first and then it doesn't update.
See console for details.

Am I doing something wrong here ?

**Comment by robmadole** [comment]
Fantastic! Thanks @WaSa42 . I'll take a look at this ASAP. Thank you for putting together this example.

**Comment by robmadole** [comment]
Ok, I've confirmed @WaSa42 that updating the dependencies to the latest versions of all of the NPM packages solves the issue. Please give it a go and if you continue to have troubles we'll re-open this.
