### ISSUE TITLE
How to use it with reactjs? 

### ISSUE THREAD

**Issue by Monmoy042** [FortAwesome/react-fontawesome#505]
I am unable to use font awesome in my react projects. Is it free for use any demo projects nowadays?

Can anyone give me any good documentation to use it properly in ReactJS projects?

**Comment by robmadole** [comment]
Have you seen these @Monmoy042 ?

https://fontawesome.com/v6/docs/web/use-with/react/

**Comment by Monmoy042** [comment]
I have solved my problem
