### ISSUE TITLE
"icon" props is not working as the documentation described

### ISSUE THREAD

**Issue by namti** [FortAwesome/react-fontawesome#510]
**Describe the bug**
`<FontAwesomeIcon />` `icon` is not working as the documentation describes.
<img width="233" alt="image" src="https://user-images.githubusercontent.com/2180936/169739026-9b42600b-b316-4d1d-9626-268fb1a65980.png">

**Reproducible test case**
[Source code](https://codesandbox.io/s/react-fontawesome-forked-eblnr4?file=/src/page/App.js
)

**Expected behavior**
These `icon` props should work.

```html
<FontAwesomeIcon icon="coffee" />
<FontAwesomeIcon icon={['fas', 'coffee']} />
<FontAwesomeIcon icon={faCoffee} />
```

**Desktop (please complete the following information):**

- Chrome
- Safari
- Firefox

**Comment by Minho-Lee** [comment]
According to the docs, if you want to use `icon="coffee"` or `icon={['fas', 'coffee']}` format, you have to add icons globally first. 

So in your code snippet, if you add,
```
import { fas, faCoffee } from "@fortawesome/free-solid-svg-icons";
import { library } from '@fortawesome/fontawesome-svg-core';
```
and
```
componentDidMount() {
    library.add(fas, faCoffee);
  }
```

You will see 
![Screen Shot 2022-05-26 at 10 22 10 AM](https://user-images.githubusercontent.com/22223772/170507357-e92d8f89-3334-4e5e-9c0f-3acf6f8fdd19.png)


For more info, [here](https://fontawesome.com/v6/docs/web/use-with/react/add-icons#add-icons-globally)

**Comment by namti** [comment]
Thanks @Minho-Lee
