### ISSUE TITLE
Needless re-binding of a function on every render

### ISSUE THREAD

**Issue by gnapse** [FortAwesome/react-fontawesome#52]
It seems to me that the resulting `convertCurry` function in [this line](https://github.com/FortAwesome/react-fontawesome/blob/59b09c7c9e78bed4b169959d0ff821d07dafe544/src/components/FontAwesomeIcon.js#L69) does not depend on any prop or anything variable or specific to the particular `FontAwesomeIcon` instance, so why re-compute it on every render? Couldn't it be extracted out of  the component and be a constant within that file?

**Comment by mlwilkerson** [comment]
@gnapse I published a prerelease that includes your recommended change. Can you have a look at it and provide any further feedback?

`@fortawesome/react-fontawesome@0.1.0-2`

**Comment by gnapse** [comment]
Looks good to me.
