### ISSUE TITLE
svelte-fontawesome implementation

### ISSUE THREAD

**Issue by seantimm** [FortAwesome/react-fontawesome#521]
I built an implementation for svelte based off this repo and would love to help coordinate making it official (if anyone is interested).  If someone is able to help draw attention to it to the right people, it's located here:

https://github.com/seantimm/svelte-fontawesome

It works identically to this React implementation and all the same unit tests pass (other than ref because I haven't figured out how to test that one, yet, but the implementation is there).  I still need to get Svelte-equivalent examples in as well.

**Comment by robmadole** [comment]
I've replied to @seantimm via email on this. Just so folks know this looks great and we are interested in making it official. I'll work with Sean and see if we can work out the details.
