### ISSUE TITLE
IconProp type not exported!

### ISSUE THREAD

**Issue by erikbergsten** [FortAwesome/react-fontawesome#527]
**Describe the bug**
To to create a component which uses a fontawesome-react icon in typescript you need the IconProp type from fontawesome-react! It currently isn't exported so you have to cast-as-any to pass typechecking (and my OPO will kill me if I do).

**Reproducible test case**
Simple enough

    import { IconProp } from '@fortawesome/react-fontawesome';

results in: `TS2459: Module '"@fortawesome/react-fontawesome"' declares 'IconProp' locally, but it is not exported.`

**Expected behavior**
The type should be imported

**Additional info**
snippet from package.json:

        "@fortawesome/react-fontawesome": "^0.2.0",

**Comment by robmadole** [comment]
Try `import { IconProp } from '@fortawesome/fontawesome-svg-core';`
