### ISSUE TITLE
Server Side Render Issue

### ISSUE THREAD

**Issue by mattoni** [FortAwesome/react-fontawesome#53]
When rendering on the server side, there is no way to get the style sheet that is loaded by the font awesome component and send it over with the request.

this is causing my icons to "jump" in size as the styles are applied since the server renders them large, then they are rendered again when react kicks in and the new styles are applied.

Could you create a method to extract out the styles so they can be included by the servers HTML response?

**Comment by RustyDev** [comment]
I'm having the same problem and was able to solve it by setting a width and height in my scss.

**Comment by robmadole** [comment]
Please check https://fontawesome.com/how-to-use/server-side-rendering#css

**Comment by maxkrieger** [comment]
If you're using Gatsby, you can use this plugin https://www.gatsbyjs.org/packages/gatsby-plugin-fontawesome-css/ by @jzabala
