### ISSUE TITLE
Self Host Font Awesome with TypeScript?

### ISSUE THREAD

**Issue by kiastorm** [FortAwesome/react-fontawesome#553]
**Is your feature request related to a problem? Please describe.**
I'm a Pro subscriber trying to self-host the font awesome SVG / JS assets via a private NPM package.

I'm following the guide here: https://fontawesome.com/v6/docs/web/setup/host-yourself/svg-js

But the font awesome for web download doesn't contain TypeScript declarations, but they are included in the official font awesome npm packages. Is there somewhere I can find these?

**Describe the solution you'd like**
I'd like TypeScript declarations to self host FA.

**Comment by xiadongdev** [comment]
Any update on this? We're having the same issue

**Comment by robmadole** [comment]
You can use `npm pack` to download the NPM packages and then host these yourself.

**Comment by benmcginnis** [comment]
@robmadole I just tried this and it doesn't include the typescript sources, just the same JS that you get when you download from the fort-awesome website.
