### ISSUE TITLE
Warning: React.createElement: type is invalid 

### ISSUE THREAD

**Issue by noamalffasy** [FortAwesome/react-fontawesome#56]
This error shows up when I'm using next.js

```Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.```

**Comment by noamalffasy** [comment]
OK, I got it fixed,
I had to import it this way:
```js
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
```
instead of:
```js
import FontAwesomeIcon from "@fortawesome/react-fontawesome";
```

**Comment by noamalffasy** [comment]
OK, I got it fixed,
I had to import it this way:
```js
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
```
instead of:
```js
import FontAwesomeIcon from "@fortawesome/react-fontawesome";
```

**Comment by robmadole** [comment]
Yep, `import { FontAwesomeIcon } ` is going to be the recommended way going forward.

**Comment by joaokamun** [comment]
Trying to import from both ways, still getting the same error than @noamalffasy.

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Comment by robmadole** [comment]
Can anyone publish a codesandbox.io or similar? I'll take a look.

**Comment by joaokamun** [comment]
Just an update, the following worked too:

`import * as FontAwesomeIcon from '@fortawesome/react-fontawesome'`

@robmadole Im not at the office right now.. Later I can do!
