### ISSUE TITLE
Two react apps, only one can import fonts

### ISSUE THREAD

**Issue by frkboak** [FortAwesome/react-fontawesome#561]
**Describe the bug**
We have two react apps running on the same page, each of which is importing FontAwesomeIcon from @fortawsome/react-fontawesome and fonts from @fortawesome/pro-regular-svg-icons.

When just one of the react apps is running on a page, icons display just fine.

When both react apps are running on the same page, only one is able to display icons. In the other one, we get `undefined` for any icons we import from @fortawesome/pro-regular-svg-icons

(we tested importing free icons and they have the same problem)

**Reproducible test case**
Can't really share sample code, sorry.

**Expected behavior**

**Desktop (please complete the following information):**

Windows 10

- Brave
- 1.65.114

(also Chrome 124.0.6367.156 and Firefox 125.0.3)

**Additional context**

**Comment by sachinrepaswal** [comment]
Try isolating the imports of `@fortawesome/react-fontawesome` and `@fortawesome/pro-regular-svg-icons` within each React app. This means that each app should have its own instance of these imports, rather than sharing them globally.

**Comment by frkboak** [comment]
thanks. sounds like I probably need to teach myself webpack, which is what we're using to build these apps

**Comment by robmadole** [comment]
I can re-open this if there turns out to be a problem with this library.
