### ISSUE TITLE
0.2.1 defaultProps migration introduces breaking change

### ISSUE THREAD

**Issue by mmaloon** [FortAwesome/react-fontawesome#562]
**Describe the bug**
Release 0.2.1 introduces bug where explicitly passing `undefined` as a className causes an error

**Reproducible test case**
[Codepen Demo](https://codepen.io/mikemaloon/pen/VwOeaaj)

**Expected behavior**
This has potential to break existing code. Maybe revert and save for a major release?

This code works for version 0.2.0 but not on 0.2.1
`<FontAwesomeIcon className={undefined} icon={faUser} />`

**Comment by mmaloon** [comment]
https://github.com/FortAwesome/react-fontawesome/pull/559

**Comment by shehi** [comment]
Regardless of any PRs, this issue should exist.

The usage of `.split()` function contradicts TS typing of `className` props which is nullable:

![image](https://github.com/FortAwesome/react-fontawesome/assets/653569/f1eef926-33f1-417a-8512-5d1aea1c2035)

**Comment by robmadole** [comment]
Thanks, I'll take a look at this.

**Comment by robmadole** [comment]
Just released 0.2.2. Please give this a try.
