### ISSUE TITLE
config.autoAddCss = false does not work in Nextjs app dir with SSR

### ISSUE THREAD

**Issue by isaacrowntree** [FortAwesome/react-fontawesome#568]
**Describe the bug**
Double-loading CSS for fontawesome in NextJS with config.autoAddCss set to false

**Reproducible test case**
You can see it here: https://campermate.com/

<img width="510" alt="Screenshot 2024-10-15 at 5 46 34 pm" src="https://github.com/user-attachments/assets/9f1ec372-2796-4751-b2d1-ee2b65e513a1">

<img width="646" alt="Screenshot 2024-10-15 at 5 47 01 pm" src="https://github.com/user-attachments/assets/2d1b4426-9a29-4806-81ec-9d2ec4c2966b">

**Expected behavior**
Only the NextJS CSS should have FontAwesome CSS.

**Additional context**
If I don't have the NextJS CSS I get the flash of large iconography bug.

This is my root layout:

```
import { Viewport } from 'next'
import { config } from '@fortawesome/fontawesome-svg-core'

config.autoAddCss = false

import './global.scss'

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>
}
```

And this is `global.scss`

```
@import "@fortawesome/fontawesome-svg-core/styles.css";
```

As a side note - would be nice to know if you can provide a minified version of this.

**Comment by robmadole** [comment]
@isaacrowntree can you provide a reproducible example of this?

**Comment by isaacrowntree** [comment]
@robmadole I showed you on my website...

**Comment by robmadole** [comment]
@isaacrowntree sorry. An example that we can run locally for debugging purposes. Because we can't modify and inspect the build process it makes it tough to figure out the issue.

**Comment by MarkA772** [comment]
I was having an issue with getting double styles on nextjs as well. It looks like setting autoAddCss on a server side page doesn't affect client side pages.

Once I set autoAddCss on a client component in my layout it worked properly for me.

```
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;
```

**Comment by isaacrowntree** [comment]
Thanks @MarkA772 that did it for me.

**Comment by ambethia** [comment]
If anyone else finds this later, that client component needs to get loaded _before_ any icons are rendered. I have a wrapper `Icon` component, and even putting the `config.autoAddCss = false` in there with 'use client' didn't do the trick. This is what I came up with:

A `FontAwesome` component:

```
'use client'

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false

export const FontAwesome = () => <></>
```

Then load that in the layout, before the body (or at least before `{children}`:

```
import { FontAwesome } from '@/components/ui/FontAwesome'
import '@/app/globals.css'

export default function RootLayout({ children } {
  return (
      <html lang="en">
        <FontAwesome />
        <body>
          {children}
        </body>
      </html>
  );
}
```
