### ISSUE TITLE
Icons not Working

### ISSUE THREAD

**Issue by iharmanpannu** [FortAwesome/react-fontawesome#64]
Only the icons showed in the examples work. I wanted to use copyrights icon and some other ones none of those worked. Just the brand names icons works.

**Comment by robmadole** [comment]
@iharmanpannu have you added the additional icons to the library with `fontawesome.library.add`?

**Comment by sant123** [comment]
Try this
```jsx
import React from "react";
import FontAwesomeIcon from "@fortawesome/react-fontawesome"
import * as Icons from "@fortawesome/fontawesome-free-solid"

export default class HomeComponent extends React.Component {

  constructor(props) {
    super(props);

    this.state = { greeting: "Hello world :)" };
  }

  render() {
    return (
      <div>
        <p>{this.state.greeting}</p>
        <FontAwesomeIcon icon={Icons.faCopyright} size="6x" />
      </div>
    );
  }
}
```

**Comment by iharmanpannu** [comment]
@sant123 It worked thanks. Another question what If I want to add any other icon will this method work?

**Comment by iharmanpannu** [comment]
I tried it works thanks again @sant123

**Comment by gregorypothier** [comment]
thanks @sant123 this worked for me as well with brands:

`import * as Brands from '@fortawesome/free-brands-svg-icons';`

**Comment by jtla3** [comment]
I am having the same issue and nothing stated above works. Can someone help?

```
import React from 'react';
import { Link } from 'react-router-dom';

// import Styles
import './header.css';
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
import * as Icons from '@fortawesome/fontawesome-free-solid';

const Header = () => {

    //  Function for logo bars
    const navBars = () => (
        <div className="bars">
            <FontAwesomeIcon icon={Icons.faBars}/>
        </div>
    )

    // Function to return logo
    const logo = () => (
            <Link to="/" className="logo">
                <img src="/images/nba_logo.png" alt="nba logo"/>
            </Link>
    )


    return (
        <header className="header-layout">
            <div className="header-div">
                {navBars()}
                {logo()}
            </div>
        </header>
    );
};

export default Header;
```
Error message
./src/components/Header/header.js
Attempted import error: '@fortawesome/react-fontawesome' does not contain a default export (imported as 'FontAwesomeIcon').

**Comment by oliakuzyura** [comment]
@jtla3 Have you find the answer?

**Comment by RanaAlqrenawi** [comment]
@jtla3 @oliakuzyura I had the same issue just this afternoon and it's simply sorted by replacing the import statement you have by this one: **_import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";_**

So, it's just making sure to keep the **FontAwesomeIcon**  between **{}**.

**Comment by ivandosreisandrade** [comment]
This solution worked for me, but I also had to install a missing dependency
`
npm i --save @fortawesome/fontawesome-svg-core
`

Many thanks

> @jtla3 @oliakuzyura I had the same issue just this afternoon and it's simply sorted by replacing the import statement you have by this one: **_import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";_**
> 
> So, it's just making sure to keep the **FontAwesomeIcon** between **{}**.

**Comment by designeralabi** [comment]
I  ran into the same issue for hours even though my code was right, it still didn't work until I gave it a styling of width and height. so if you ran into same issue tried to give it a styling and see if this fixed the problem
