### ISSUE TITLE
Is This Package Compatible With Pro License

### ISSUE THREAD

**Issue by webjunkie01** [FortAwesome/react-fontawesome#65]
Hi,

I've a pro license and would like to know if this package is compatible.

Cheers.

**Comment by webjunkie01** [comment]
Ah nevermind...

**Comment by kuuup-at-work** [comment]
Share your mind :smile:

**Comment by webjunkie01** [comment]
Oh, well after I created the issue found the instructions in the docs section 😊. I think it will be a good idea to publish the instructions for the PRO version here on the repo. 

Cheers

**Comment by leotm** [comment]
If [this](https://github.com/FortAwesome/react-fontawesome#add-more-styles-or-pro-icons) could get mentioned in [this](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers), it could save new devs a lot of time.
