### ISSUE TITLE
Add types for TypeScript

### ISSUE THREAD

**Issue by Skovy** [FortAwesome/react-fontawesome#66]
Currently, there are no types for TypeScript.

I'm not sure if that should live in this repo, DefinitelyTyped or in https://www.npmjs.com/package/@fortawesome/fontawesome-common-types? 

With a bit of guidance (where they belong and best practices for the project) I'd be happy to open a PR  to add type support.

**Comment by robmadole** [comment]
We'll be working on this as part of our 5.1 release. For the time being @Skovy don't invest any work. The API has changed slightly and it's all a bit of a rats nest that @mlwilkerson and I need to unravel.

**Comment by mlwilkerson** [comment]
@Skovy actually, there _are_ types. Check out the development branch:
https://github.com/FortAwesome/react-fontawesome/tree/development

There's also an npm pre-release. Try: 
`@fortawesome/react-fontawesome@0.1.0-2`

It would be great if you could try the pre-release and provide feedback.

**Comment by Skovy** [comment]
Ah, perfect. I'll give this a look! 👌 Appreciate the pointer!

**Comment by tx4x** [comment]
there is no index.d.ts in @fortawesome/react-fontawesome@0.1.0-2

**Comment by robmadole** [comment]
Try 0.1.0-3 @tx4x
