### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by jducro** [FortAwesome/react-fontawesome#67]
```
ERROR in ./node_modules/@fortawesome/react-fontawesome/src/components/FontAwesomeIcon.js
Module parse failed: Unexpected token (57:4)
You may need an appropriate loader to handle this file type.
| 
|   const renderedIcon = fontawesome.icon(icon, {
|     ...classes,
|     ...transform,
|     ...mask,
```

I get the following error when I try to use `react-fontawesome` do you have an idea what could be wrong?

**Comment by robmadole** [comment]
This is ES6 so it requires Babel or similar transpiler if you are running this in older Node.js or browser environments.

Are you trying to import or requires that file directly? You should be doing something like this instead:

```
import FontAwesomeIcon from '@fortawesome/react-fontawesome'
```

**Comment by jducro** [comment]
My bad, I was importing the file directly, stupid auto import from my IDE.

Thanks for pointing that out.

**Comment by robmadole** [comment]
No worries!
