### ISSUE TITLE
Typescript defs

### ISSUE THREAD

**Issue by timc13** [FortAwesome/react-fontawesome#68]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-fontawesome are hopelessly out of date

**Comment by robmadole** [comment]
Hi @timc13. That's not our project, sorry. We're working on type definitions and you can install a pre-release that includes them from [this branch](https://github.com/FortAwesome/react-fontawesome/tree/development).

**Comment by timc13** [comment]
I installed the `0.1.0-2` prelease version from npm, but `index.d.ts` is missing.  Seems it's missing in your publishing pipeline ...

**Comment by robmadole** [comment]
Doh! Sure enough. Try 0.1.0-3.

**Comment by kirkbross** [comment]
Can you release a **0.1.0-9** that includes `color?: string;` in the the interface? :D

**Comment by robmadole** [comment]
0.1.0-9 released!

**Comment by kirkbross** [comment]
Sweet! :D

**Comment by kirkbross** [comment]
Is there any ETA on a 1.0.0 release?

**Comment by robmadole** [comment]
@kirkbross we'll officially release the 0.1.0 when our larger effort for version 5.1 of FA is ready to roll. It's available for testing and we've been asking folks to help us test. We're just waiting for a bit to make sure nothin big pops up.

**Comment by kirkbross** [comment]
Cool. Thanks!
