### ISSUE TITLE
View config not found for name path

### ISSUE THREAD

**Issue by knightjdr** [FortAwesome/react-fontawesome#69]
I'm trying to use the pro package in my react-native app.

I'm importing and using like so:

```javascript
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
import faCoffee from '@fortawesome/fontawesome-pro-solid/faCoffee';

const MyComponent = () => (
  <View>
    <FontAwesomeIcon icon={faCoffee} />
  </View>
);
```

I get the error:

"Invariant Violation: View config not found for name path

This error is located at:
    in path (created by FontAwesomeIcon$1)
    in svg (created by FontAwesomeIcon$1)
    in FontAwesomeIcon$1 (at mycomponent.js:6)"

Is this something I'm doing wrong or an incompatability with react-native possibly? I've also tried building a library instead and get the same error.

**Comment by knightjdr** [comment]
Further digging suggests this may have to do with react native expecting all components to begin with a capital letter. Does the <FontAwesomeIcon> component  contain any children that violate this? I've been looking through the package, focusing on FontAwesomeIcon$1, but haven't figured it out yet.

**Comment by robmadole** [comment]
We don't support React Native yet. Sorry. This is on the list but we haven't even started on it yet.

**Comment by vincent-louis** [comment]
there is a very light implementation using react-native-svg, can have a look at [react-native-fontawesome-pro](https://github.com/shyaniv7/react-native-fontawesome-pro) as a temporary solution

**Comment by alsemyonov** [comment]
@robmadole, is there insight on when we could start using FontAwesome icons in React Native apps using the `react-fontawesome` package?

**Comment by robmadole** [comment]
@alsemyonov have you tried https://github.com/FortAwesome/react-native-fontawesome?

**Comment by alsemyonov** [comment]
Oh, nice! I need to try that. Thank you!
