### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by kbzowski** [FortAwesome/react-fontawesome#70]
According to readme using explicit import like 
`import faCoffee from '@fortawesome/fontawesome-free-solid/faCoffee'`
should allow to minimalize bundle size. What sizes should I expect? 
I am using around 15 icons from fontawesome-free-solid. All of them were imported using explicit import. According to source-map-explorer, fontawesome-free-solid occupy 610 KB in my case. Is it normal?

![firefox_2018-02-09_07-49-17](https://user-images.githubusercontent.com/2268743/36015369-6ad0c60c-0d6e-11e8-9cdc-da054eb4ae04.png)

**Comment by navarroaxel** [comment]
The docs for `@fortawesome/react-fontawesome` says
> Explicit Import
> 
> Allows icons to be subsetted, optimizing your final bundle. Only the icons you import are included in the bundle. However, explicitly importing icons into each of many components in your app might become tedious, so you may want to build a library.

I'm using this notation
```javascript
import {faTrashAlt} from '@fortawesome/fontawesome-free-regular';
```
but the result is the whole `index.es.js` file in my bundle.

Things I tried:
1. Removing the `default export` of the `index.es.js` but the result is the whole file.
2. Individualizing the naming `export`. From this:
```javascript
export {prefix, faAddressBook, faAddressCard, faAdjust, faAlignCenter, ...};
```
to this:
```javascript
export {prefix};
export {faAddressBook};
export {faAddressCard};
export {faAdjust};
export {faAlignCenter};
...
```

I can't find a workaround to make webpack reduce the the `@fortawesome/fontawesome-free-regular` size, the same with `@fortawesome/fontawesome-free-solid`.

**Comment by iagomelanias** [comment]
@navarroaxel try to use:
```js
import faTrashAlt from '@fortawesome/fontawesome-free-regular/faTrashAlt';
```

Webpack will only import the icon you are actually referencing.

**Comment by robmadole** [comment]
We'll be addressing some tree-shaking issues in the 0.1.0 release of this library. Hang tight and we'll get this solved.

**Comment by pleunv** [comment]
> but the result is the whole index.es.js file in my bundle.

As far as I can tell that is the core fontawesome lib, so that'll always be there.

I love the approach v5 is taking but I'm a little bit worried that so much runtime code is needed for rendering an icon, I feel a little bit uneasy replacing 80kb of material icon fonts with 60kb of icon-rendering logic. Are there plans to slim this down or possibly provide separate entry-points for simpler use-cases?

**Comment by robmadole** [comment]
Yep, @pleunv, we have an entire track that is focused on optimization. We intend on moving the rendering logic into a set of modules that can be elective. That plugin kind of architecture is probably a long way off though.

**Comment by pleunv** [comment]
Sounds great, looking forward to it :)

**Comment by edmorley** [comment]
I'm presuming the reason the shorter explicit import version (eg `import {faTrashAlt} from '@fortawesome/fontawesome-free-regular'`) doesn't work is similar to that affecting lodash/others in webpack/webpack#2867? 

ie: Defining `"side-effects": false` in react-fontawesome's package.json (presuming there are no side-effects) will allow for full tree-shaking with webpack 4, or else use the longer import form in the meantime.

**Comment by navarroaxel** [comment]
I have added `"sideEffects" false` using Webpack@4 and the bundle size is not smaller.

**Comment by navarroaxel** [comment]
@kzc give me the solution here: https://github.com/webpack/webpack/issues/6724#issuecomment-372192614
This line of code prevents unused definitions from being dropped:
```js
define('fas', icons$1);
```
@robmadole, How we can fix this?

**Comment by robmadole** [comment]
This will be addressed in 5.1.0 of Font Awesome. We are working on this now and it’s the highest priority item we have for the dev team.

**Comment by mlwilkerson** [comment]
For those who are eager about the upcoming changes for tree shaking, but maybe haven't yet experimented with it on the `development` branch, here's an appetizer: a working demo of easy tree shaking.
https://github.com/mlwilkerson/react-fontawesome-tree-shaking-demo

**Comment by gerhardsletten** [comment]
You can also shave off a 15kb gzipped by just using the svg-icon directly and use your own `css-in-js` solution, this is an example with `styled-components`:

```es6
import React from 'react'
import PropTypes from 'prop-types'
import styled, { css } from 'styled-components'

import basket from '@fortawesome/fontawesome-free-solid/faShoppingCart'
import bar from '@fortawesome/fontawesome-free-solid/faBars'
import left from '@fortawesome/fontawesome-free-solid/faChevronCircleLeft'
import right from '@fortawesome/fontawesome-free-solid/faChevronCircleRight'
import down from '@fortawesome/fontawesome-free-solid/faChevronCircleDown'
import up from '@fortawesome/fontawesome-free-solid/faChevronCircleUp'
import email from '@fortawesome/fontawesome-free-solid/faEnvelope'
import check from '@fortawesome/fontawesome-free-solid/faCheck'

import facebook from '@fortawesome/fontawesome-free-brands/faFacebook'
import instagram from '@fortawesome/fontawesome-free-brands/faInstagram'
import pinterest from '@fortawesome/fontawesome-free-brands/faPinterest'
import youtube from '@fortawesome/fontawesome-free-brands/faYoutube'

import Element from '../Element/Element'

const icons = {
  email,
  check,
  facebook,
  instagram,
  youtube,
  pinterest,
  basket,
  bar,
  'arrow-left': left,
  'arrow-right': right,
  'arrow-down': down,
  'arrow-up': up
}

const IconBase = styled.svg`
  height: 1em;
  width: 1em;
  margin: 0 !important;
`

const Container = Element.withComponent('i').extend`
  display: inline-flex;
  align-self: center;
  position: relative;
  height: 1em;
  width: 1em;
  vertical-align: baseline;
  ${props =>
    props.baseline
      ? css`
          ${IconBase} {
            bottom: -0.125em;
            position: absolute;
          }
        `
      : ''}
`

const Icon = ({ icon, ...rest }) => {
  if (!icons[icon]) {
    return null
  }
  const rawIcon = icons[icon]
  return (
    <Container {...rest}>
      <IconBase
        aria-hidden='true'
        role='img'
        xmlns='http://www.w3.org/2000/svg'
        viewBox='0 0 512 512'
      >
        <path fill='currentColor' d={rawIcon.icon[4]}></path>
      </IconBase>
    </Container>
  )
}

Icon.propTypes = {
  icon: PropTypes.oneOf(Object.keys(icons)).isRequired,
  baseline: PropTypes.bool
}

export default Icon

```

**Comment by robmadole** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/FortAwesome/react-fontawesome/issues/70](https://trello.com/c/85Uxhu93/96-https-githubcom-fortawesome-react-fontawesome-issues-70)

**Comment by kbzowski** [comment]
Is the issue definitively solved? As for me, the current version (1.1.6) is OK. The size of the @fortawesome after build (in my case) is limited to 46 KB, which is a great improvement.

**Comment by pleunv** [comment]
@robmadole That link brings me to trello but it doesn't show any boards :)

**Comment by navarroaxel** [comment]
@kbzowski the current version `latest` or the `prerelease` channel explained here: https://github.com/FortAwesome/react-fontawesome/tree/development ?

**Comment by robmadole** [comment]
@pleunv that Trello link is just for our internal tracking, ignore please.

**Comment by kbzowski** [comment]
@navarroaxel Current from npm registry

**Comment by IanVS** [comment]
Hi, now that `0.1.0` / `5.1.0` is released, is webpack treeshaking working properly?

**Comment by robmadole** [comment]
Try `import { faAngleDoubleRight } from '@fortawesome/free-solid-svg-icons/faAngleDoubleRight'`.

Also check out the docs here regarding the issue with slow tree shaking. https://fontawesome.com/how-to-use/with-the-api/other/tree-shaking

**Comment by robmadole** [comment]
Going to close this as we've got this implemented in 5.1.0.

**Comment by leoyli** [comment]
@robmadole 

Thanks, that works, but as I said I got errors `TypeError: Cannot read property 'prefix' of undefined` in the bundle.js... when I try to execute my app.  Any hints?!  It's because I use the brand icons?

**Comment by mhriess** [comment]
Is tree shaking supported for the FA pro libraries as well? I'm using @fortawesome/pro-light-svg-icons 5.2.0 and named imports still results in the entire FA library included in my bundle. Thanks!

**Comment by robmadole** [comment]
@mhriess yes, it's supported in Pro. If you are having issues with your build tool we suggest going to sub-module imports like `import { faAngleDoubleRight } from '@fortawesome/free-solid-svg-icons/faAngleDoubleRight'`

**Comment by mhriess** [comment]
Thanks @robmadole - we fell back to the submodule import, just wanted to double check we weren't doing anything wrong.

**Comment by ryanwalters** [comment]
We weren't able to get tree shaking to work out of the box with Webpack 4. Thankfully, we were able to workaround the issue using [babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports) with a configuration like this:

```json
// .babelrc
{
  "plugins": [
    ["transform-imports", {
      "@fortawesome/free-solid-svg-icons": {
        "transform": "@fortawesome/free-solid-svg-icons/${member}",
        "skipDefaultConversion": true
      }
    }]
  ]
}
```

With that, we're still able to import members directly from the package.
```js
import { faTimes, faEnvelope } from '@fortawesome/free-solid-svg-icons';
```

This works for Pro versions as well.

**Comment by mattoni** [comment]
I'm having an issue getting my bundle size down with webpack 4 as well. The output ends up being > 1MB in size with the default webpack production build, while doing destructured imports like above. Is anyone else having this issue/resolved?

**Comment by tavurth** [comment]
> @ryanwalters This works for Pro versions as well.

Thank you for that. Using your approach I was able to reduce the parsed size of Fontawesome from over 9MB to around 300kb.

### Before
![Screenshot 2019-04-25 at 17 59 36](https://user-images.githubusercontent.com/100964/56731191-165c4300-6784-11e9-8d78-b44be7e02ea3.png)

### After
![Screenshot 2019-04-25 at 17 59 53](https://user-images.githubusercontent.com/100964/56731192-165c4300-6784-11e9-8a53-858b60e63bc6.png)

### .babelrc
```json
{
  "presets": ["@babel/env", "@babel/react", "babel-preset-expo"],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/plugin-syntax-export-namespace-from",
    [
      "transform-imports",
      {
        "@fortawesome/pro-regular-svg-icons": {
          "transform": "@fortawesome/pro-regular-svg-icons/${member}",
          "skipDefaultConversion": true
        },
        "@fortawesome/pro-solid-svg-icons": {
          "transform": "@fortawesome/pro-solid-svg-icons/${member}",
          "skipDefaultConversion": true
        },
        "@fortawesome/pro-light-svg-icons": {
          "transform": "@fortawesome/pro-light-svg-icons/${member}",
          "skipDefaultConversion": true
        }
      }
    ]
  ]
}
```

**Comment by hugomassing** [comment]
Any updates? It doesn't work with create-react-app as well.

**Comment by RobertBMerriman** [comment]
If you are trying to implement @ryanwalters's solution but are using a `babel.config.js` you have to use a function like so:

```javascript
plugins: [
  ...
  [
    'transform-imports',
    {
      '@fortawesome/free-solid-svg-icons': {
        transform: member => `@fortawesome/free-solid-svg-icons/${member}`,
        skipDefaultConversion: true,
      },
    },
  ],
]
```
---
Also as an aside if you currently use `fas` as a way to get icons via their string name, importing this will cause an error and cannot be used. (Also, now it simply won't function as it won't have reference to all the icons you are now no longer importing)

**Comment by feederaccount** [comment]
I am dealing with this now after upgrading from Font Awesome 4 (painlessly referenced with a <link> tag via a CDN) to Font Awesome 5 with React.

I am importing a single icon. My bundle grew from 300KB without Font Awesome to over 1MB with it. I followed the advice of doing:

import { faDollarSign } from "@fortawesome/free-solid-svg-icons**/faDollarSign**";

...and it shaved it down to 700KB, but that's still **400KB for a single icon**. This is absurd.. the whole point of importing single icons is to reduce bundle sizes.

Here's my code:

```
import { icon } from '@fortawesome/fontawesome-svg-core';
import { faDollarSign } from "@fortawesome/free-solid-svg-icons/faDollarSign";

const dollarSign = icon(faDollarSign).html;
```

**Comment by tavurth** [comment]
Switched to [styled-icons](https://styled-icons.js.org/) a while ago because of this issue and never looked back...
