### ISSUE TITLE
question

### ISSUE THREAD

**Issue by soniapello** [FortAwesome/react-fontawesome#71]
it's a question not an issue
 I'm searching all font-awesome-free-solid list like faCoffee ... 
Does that list exist ?

**Comment by NateRadebaugh** [comment]
The search function in the main website allows you to filter to only things that are "solid":
* https://fontawesome.com/icons?d=gallery&s=solid&m=free

**Comment by soniapello** [comment]
Thanks @NateRadebaugh
Do you know if a @fortawesome/fontawesome-free exist because 
  I try to import all free icons as Icons and I had to used @fortawesome/fontawesome-free-solid,@fortawesome/fontawesome-free-regular,@fortawesome/fontawesome-free-brand and @fortawesome/fontawesome-free-light

**Comment by NateRadebaugh** [comment]
I don't think so. https://www.npmjs.com/search?q=%40fortawesome

**Comment by robmadole** [comment]
We separate these into different styles and packages to reduce download size for people who are just using one of the styles.
