### ISSUE TITLE
babel presets: "es2015" deprecated, using "env" is recommended?

### ISSUE THREAD

**Issue by m4v15** [FortAwesome/react-fontawesome#73]
from the babel docs: https://babeljs.io/docs/plugins/preset-es2015/

I had a compile error as I was using `env` instead, should I have the "es2015" preset for this library?

**Comment by balestrinc** [comment]
I have the same issue.

**Comment by m4v15** [comment]
@balestrinc I deleted "es2015" from their presets and added "stage-3" to my own and it works fine. (apparently "env" doesn't support stage-x plugins: https://github.com/babel/babel-preset-env/issues/14)

**Comment by robmadole** [comment]
@m4v15 @balestrinc what do your imports look like? I'm upgrading to `env` but I'm trying to decide if we even include the `.babelrc` file as part of the module package.

**Comment by robmadole** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Env instead of es2015](https://trello.com/c/YaoLO5OK/19-env-instead-of-es2015)

**Comment by robmadole** [comment]
We've switched to `babel-env` in the `development` branch.
