### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by johnnunns** [FortAwesome/react-fontawesome#74]
Originally solved with text-shadow in css. But now since it's an svg, text-shadow doesn't give us anything. Do we have a solve here?

**Comment by robmadole** [comment]
Hi @johnnunns SVG doesn't support text shadow so we don't have a solution yet. Sorry.

**Comment by MarkReeder** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/drop-shadow

**Comment by sean256** [comment]
@robmadole does this mean that react-fontawsome only supports the svg library?

**Comment by robmadole** [comment]
@sean256 yep, if you want web fonts and CSS you really don't need a separate React component.
