### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by tashburn** [FortAwesome/react-fontawesome#75]
I'm using node/Next.js and getting an error during server-side rendering --

```
Could not find icon { prefix: 'fas', iconName: 'home' }
```

I tried the suggestions in Issue #36, but they didn't work for me.

Any suggestions?

**Comment by robmadole** [comment]
Have you added the `home` icon to the library? Like:

```
import faUser from '@fortawesome/fontawesome-free-solid/faUser'

fontawesome.library.add(faUser)
```

Please post a codesandbox.io example if this is still not working for you.
