### ISSUE TITLE
Icon Size < 1x

### ISSUE THREAD

**Issue by lightninglu10** [FortAwesome/react-fontawesome#79]
Hey guys, how do I get an icon size < 1x? I'm trying 

```
<FontAwesomeIcon
          icon="info"
          color="#ff5370"
          size=".5x"
        />
```

But this isn't working.

**Comment by robmadole** [comment]
Hey @lightninglu10 you can try using Power Transforms:

https://fontawesome.com/how-to-use/svg-with-js#power-transforms

```
<FontAwesomeIcon icon="spinner" transform="shrink-8" />
```

**Comment by edencorbin** [comment]
can't seem to get any sizing to take any effect:
<FontAwesomeIcon transform="grow-6" icon="home" />

does nothing... what might I be doing wrong?
