### ISSUE TITLE
Support for FontAwesome 5 Pro

### ISSUE THREAD

**Issue by JonAbrams** [FortAwesome/react-fontawesome#81]
Does this support FontAwesome 5 Pro? e.g I need light fonts, does this provide those?

**Note:** I've already paid for the Pro upgrade, I'm just looking at reducing the 1.5MB foot-print of the pro version's js file.

**Comment by robmadole** [comment]
This does support Pro. We have a private npm server that you can get access to in order to install the pro npm packages. Head to https://fontawesome.com/account/linked-accounts and go from there

**Comment by robmadole** [comment]
Try https://fontawesome.com/account/services
