### ISSUE TITLE
typescript icon names missing?

### ISSUE THREAD

**Issue by sheam** [FortAwesome/react-fontawesome#83]
I am using @fortawesome/react-fontawesome": "0.1.0-3", the IconName type seems to be missing a few like repeat, rectangle-portrait, for example are both missing.

Are there plans to add all the icons? Or is a PR needed?

~S

**Comment by robmadole** [comment]
Sure enough @sheam. We'll take a look.

**Comment by sheam** [comment]
FYI: fal, sign-in missing too.

Note for others who find this, the workaround is to cast to _any_:  `<FontAwesomeIcon icon={['fal', 'sign-in' as any]} />'

**Comment by robmadole** [comment]
This should be all fixed up in `@fortawesome/fontawesome@1.1.4` and `@fortawesome/fontawesome-common-types@0.1.3`

**Comment by sheam** [comment]
My package.json currently has these lines:
```
    "@fortawesome/fontawesome": "^1.2.0-2",
    "@fortawesome/react-fontawesome": "0.1.0-3",
```
which already seems to be ahead of what you are proposing.... I do not have fontawesome-common-types0.1.3, maybe that is my problem?

**Comment by robmadole** [comment]
It's gonna be in the `fontawesome-common-types` package. Can you try that?

**Comment by sheam** [comment]
the following seems to work:

![image](https://user-images.githubusercontent.com/1779211/37444935-2e1e53ce-27da-11e8-9966-6e8f79c543d1.png)

**Comment by SomethingSexy** [comment]
Did you have this issue with brand icons? I am using your same setup with TypeScript and it cannot find "fort-awesome" as an icon.

Could not find icon {prefix: "fas", iconName: "fort-awesome"}

**Comment by robmadole** [comment]
The prefix will be `fab` for the Brands style @SomethingSexy

**Comment by SomethingSexy** [comment]
Hmm, so this is what I am doing:

```
import '@fortawesome/fontawesome-free-brands';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

<FontAwesomeIcon icon="fort-awesome" />
```

Bundling via webpack.  It seems to be working for free solid icons.

**Comment by robmadole** [comment]
```
<FontAwesomeIcon icon={["fab", "fort-awesome"]}/>
```

**Comment by SomethingSexy** [comment]
Damn, I totally missed that.  Thanks!
