### ISSUE TITLE
Change colour of Icon on hover with mask

### ISSUE THREAD

**Issue by nathanjdunn** [FortAwesome/react-fontawesome#84]
I am currently using the react-fontawesome library in a project and I am trying to find a way to changing the colour of an inset icon when using a mask. In my project I have this:

```javascript
import Icon from '@fortawesome/react-fontawesome'
import { faTwitter } from '@fortawesome/fontawesome-free-brands'
import { faCircle } from '@fortawesome/fontawesome-pro-solid'

const Footer = () => (
    <Icon icon={faTwitter} size="2x" transform="shrink-6" mask={faCircle} />
)

export default Footer
```

When I hover over this icon, I would like to change the colour of the `faTwitter` icon but can't seem to find an easy way to do this when using a mask. Has anyone been able to do this yet?

Thank you 😃

**Comment by robmadole** [comment]
Hey @nathanjdunn just use CSS and switch the `class` attribute on the icon.

**Comment by nathanjdunn** [comment]
@robmadole thanks. Do you happen to know which part of the SVG I need to style in order to change the fill colour?

**Comment by SimeonC** [comment]
@nathanjdunn From the looks of it they just use `currentColor` so changing the SVG level color should do the trick.
