### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by JDWong-wag** [FortAwesome/react-fontawesome#88]
```
    "@fortawesome/fontawesome": "^1.1.4",
    "@fortawesome/react-fontawesome": "0.0.17",
```

```
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
...
<FontAwesomeIcon icon="coffee"/>
```

Produces an empty span element

**Comment by jakubboguski** [comment]
Also happend to me. It's console output.
`Could not find icon {prefix: "fab", iconName: "edit"}

log @ index.js?7fb5:450
FontAwesomeIcon$1 @ index.js?7fb5:513
updateFunctionalComponent @ react-dom.development.js?cada:7819
beginWork @ react-dom.development.js?cada:8223
performUnitOfWork @ react-dom.development.js?cada:10224
workLoop @ react-dom.development.js?cada:10288
callCallback @ react-dom.development.js?cada:542
invokeGuardedCallbackDev @ react-dom.development.js?cada:581
invokeGuardedCallback @ react-dom.development.js?cada:438
renderRoot @ react-dom.development.js?cada:10366
performWorkOnRoot @ react-dom.development.js?cada:11014
performWork @ react-dom.development.js?cada:10967
batchedUpdates @ react-dom.development.js?cada:11086
batchedUpdates @ react-dom.development.js?cada:2330
dispatchEvent @ react-dom.development.js?cada:3421`

**Comment by robmadole** [comment]
Make sure you add `faCoffee` to your library:

```
import faCoffee from '@fortawesome/fontawesome-free-solid'

fontawesome.library.add(faCoffee)
```

**Comment by JDWong-wag** [comment]
Thanks @robmadole 

Can that part be added to the example so these steps are clear to future users?

Also `fontawesome-free-solid` is missing icons that are present in the catalog (`cc-visa` for example).  Would it be possible to display this icon using `react-fontawesome`?

**Comment by robmadole** [comment]
@JDWong-wag that's part of the `fontawesome-free-brands` package
