### ISSUE TITLE
This library is so hard to use!

### ISSUE THREAD

**Issue by lightninglu10** [FortAwesome/react-fontawesome#91]
Hey guys, love fontawesome and have used your icons throughout many many projects, but the current react-fontawesome library is **_so_** hard to use. It takes me maybe 5 minutes to find the right icons, and even then sometimes I get confused and don't get the icon right.

It's really hard to find icons and what library they live in -- I'm manually going into node_modules and searching for icons because it's confusing from the website which package they're in. I also don't know the difference between free and pro and if the icons overlap there or not.

It's really hard to style icons and it's really hard to import them too. We have to put some weird `icon={["fab", "apple"]}` for icons that aren't in the regular fas package which is super confusing because the regular icons just are `icon="fa-exclamation"`. Why mix a string and an object?

Rooting for you guys to turn it around, but as nice as the new icons are, the usability is frustrating!

**Comment by robmadole** [comment]
Hey @lightninglu10 sorry to hear that this is not working out for you. We'll continue to work on the website to make that more usable, thanks for the feedback.

This React component is a low-level implementation. You are welcome to build on top of it, wrap it in your own DSL/API. There is a good reason for the `icon={["fab", "apple"]}` that we need to do a better job of documenting. (We've had [discussions about this in the Vue component](https://github.com/FortAwesome/vue-fontawesome/issues/18))

Do you have anything specific that you'd like us to work on? We are working on the import situation with 5.1.0 and hope to have that out soon.

**Comment by magicae** [comment]
I agree that this library is so hard to use. At lease for 3 points,
1. The default installed version for this library is 0.0.x which doesn't ship the index.d.ts for TypeScript users.
2. 0.1.x version seems working for TypeScript users, while the docs are totally outdated, e.g.
  - 0.1.x uses named export instead of default export
3. The example shipped with 0.1.x doesn't work at all.

**Comment by robmadole** [comment]
We've made significant updates on the [development](https://github.com/FortAwesome/react-fontawesome/tree/development) branch. The docs have been updated too. We'd love to have help testing it out and seeing how we did.
