### ISSUE TITLE
Change default prefix for font awesome

### ISSUE THREAD

**Issue by ramyajanaki** [FortAwesome/react-fontawesome#96]
I want to change the default prefix to Font Awesome Regular So tried doing

fontawesome.config = {
  familyPrefix: "far"
};
But I still have to do an "far" prefix to make it work

import React from "react";
import { render } from "react-dom";
import Hello from "./Hello";
import fontawesome from "@fortawesome/fontawesome";
import FontAwesomeIcon from "@fortawesome/react-fontawesome";
import faCalendar from "@fortawesome/fontawesome-free-regular/faCalendar";
import faSquare from "@fortawesome/fontawesome-free-regular/faSquare";

fontawesome.config = {
  familyPrefix: "far"
};

fontawesome.library.add(faCalendar, faSquare);

const styles = {
  fontFamily: "sans-serif",
  textAlign: "center"
};

const App = () => (
  <div style={styles}>
    <Hello name="CodeSandbox" />
    <h2>Start editing to see some magic happen {"\u2728"}</h2>
    Favorite beverage: <FontAwesomeIcon icon="calendar" /> //does not work
    Icon from regular: <FontAwesomeIcon icon={["far", "square"]} /> //works
  </div>
);

render(<App />, document.getElementById("root"));

https://codesandbox.io/s/40v5jk6no7

**Comment by robmadole** [comment]
The `familyPrefix` is not the same thing as the style prefix. We don't support changing the style prefix at this time. We'll most likely do this in the future but we suggest that you create a wrapper component if this is something that you need now.
