### ISSUE TITLE
Support title and have that work the same as documented accessibility features

### ISSUE THREAD

**Issue by jlismore** [FortAwesome/react-fontawesome#97]
It seems that react-fontawesome doesn't support the accessibility mode mentioned [here](https://fontawesome.com/how-to-use/accessibility).
I can use the techniques mentioned for web fonts in the docs, but it would be nice if adding a title tag to an icon made it accessible.
e.g. <FontAwesomeIcon icon="circle" title="See all things"/> would add the correct aria tags

**Comment by robmadole** [comment]
Gotcha! Thanks. We'll add this to the list.

**Comment by mmhand123** [comment]
Hi,

If it's ok, I'd like to try to add this!

**Comment by robmadole** [comment]
@mmhand123 of course. Hollar if we can answer any questions.

**Comment by robmadole** [comment]
@mmhand123 actually I'm not sure what this work is. @jlismore can you be more specific?

**Comment by mmhand123** [comment]
It looked like if we pass title to the icon function from svg-core when it makes the renderedIcon, it would work (and that function would add the title svg element with the proper aria tags), with another small change.

**Comment by sarahsmo** [comment]
Please add this! Definitely need it! @robmadole

**Comment by kishba** [comment]
@robmadole It looks like @mmhand123's merge request adds the additional property and the tests are passing. What else needs to be done before this can be merged? We're excited to add aria-labelledby to our FontAwesome icons in React!

**Comment by robmadole** [comment]
Alright folks, 0.1.3 has been released. Let us know if it does not work as expected!
